aas-core-works/aas-core-codegen

.github/workflows/ci.yml, continuous_integration/precommit.py
This patch fixes a minor mistake in the script where the jobs were
renamed, but not updated in references appropriately.
=> Fix GitHub workflow CI

CHANGELOG.rst, README.rst
* The initial release candidate.
This is actually an alpha release!
Since the UAG Verwaltungsschale still needs to decide on fundamentals
of the meta-model (such as basic primitive types) yet, this release
is only meant for first experimental usage.
=> Release 0.0.1rc1

README.rst, aas_core_codegen/main.py
This patch adds the `--version` flag to the main program so that we can
track the versions when reporting issues.
=> Add `--version` flag

aas_core_codegen/csharp/main.py, test_data/csharp/test_main/v3rc2/expected_output/types.cs, tests/csharp/test_main.py
This patch fixes the encoding when reading and writing files to UTF-8.
This is necessary so that the test files are not scrambled on Windows.
=> Fix encoding to `utf-8` on file I/O

aas_core_codegen/common.py, test_data/csharp/test_main/v3rc2/expected_output/jsonization.cs
This patch fixes the function `indent_but_first_line` to properly ignore
the empty lines and do not indent them. Only non-empty lines are
indented.
=> Make `indent_but_first_line` ignore empty lines

aas_core_codegen/intermediate/_hierarchy.py
The precondition in the hierarchy was wrong when determining the
origins. Namely, the constrained primitives *always* inherit from a
primitive type, but can be still considered as origins of the hierarchy
as long as they do not inherit from other constrained primitives.
=> Ignore primitive types for origins in hierarchy

aas_core_codegen/parse/_translate.py
This patch fixes a bug related to the order of the invariants. Namely,
the invariants are specified as decorators in a top-down order, while we
need to interpret the decorators in the reversed order (bottom-up) as
they decorate the function one by one.
=> Reverse the invariants

aas_core_codegen/csharp/structure/_generate.py, aas_core_codegen/intermediate/_stringify.py, aas_core_codegen/intermediate/_translate.py, aas_core_codegen/intermediate/_types.py, test_data/intermediate/expected/class/inheritance/expected_symbol_table.txt, test_data/intermediate/expected/class/methods_with_contracts/expected_symbol_table.txt, test_data/intermediate/expected/class/only_property_no_method/expected_symbol_table.txt, test_data/intermediate/expected/interface/basic/expected_symbol_table.txt, test_data/intermediate/expected/interface/inheritance/expected_symbol_table.txt, test_data/intermediate/expected/interface/only_constructor/expected_symbol_table.txt, test_data/intermediate/expected/real_meta_models/v3rc2/expected_symbol_table.txt, test_data/intermediate/expected/type_annotation/atomic/expected_symbol_table.txt, test_data/intermediate/expected/type_annotation/subscripted/expected_symbol_table.txt
The properties are "specified for" a class. The term "implemented for"
does not really apply and is confusing. This patch renames the attribute
accordingly.
=> Rename `implemented_for` to `specified_for`

aas_core_codegen/intermediate/_stringify.py, aas_core_codegen/intermediate/_translate.py, aas_core_codegen/intermediate/_types.py, test_data/intermediate/expected/real_meta_models/v3rc2/expected_symbol_table.txt
After this patch, we note down which classes and constrained
primitives the invariants are specified for. This allows us to consider
only the invariants specified for a particular class and ignore the
invariants inherited from the ancestors.
This will be useful when we generate schemas since invariants in the
schemas are inherited, unlike, say, C# code.
=> Note the origin of the invariants

CHANGELOG.rst, aas_core_codegen/__init__.py, setup.py
* Provide generator for JSON schema (#13)
* Improve errors on unmatched verification functions (#21)
* Note the origin of the invariants (#20)
* Rename ``implemented_for`` to ``specified_for`` (#19)
* Reverse the invariants (#18)
* Ignore primitive types for origins in hierarchy (#17)
* Fix second pass to resolve descendants correctly (#16)
* Make ``indent_but_first_line`` ignore empty lines (#15)
* Fix encoding to ``utf-8`` on file I/O (#14)
* Add ``--version`` flag (#12)
=> Release 0.0.2

README.rst, aas_core_codegen/main.py
This patch reverts unintentional changes in the commit
360c9b14d2b25cb1b8c65ef3efc794883f345e7a. We cherry-picked from the
development branch and omitted to include the logic for `--version` in
the pull request.
=> Revert lost `--version` command flag

tests/csharp/test_description.py, tests/intermediate/test_constructor.py, tests/intermediate/test_hierarchy.py, tests/intermediate/test_translate.py, tests/test_parse.py
Previously, in case of errrors in unit tests, we reported a string
representation of the error. This is unreadable and slows down the
debugging. In this patch, we report the most underlying errors formatted
as a string.
=> Report underlying messages in unit tests

aas_core_codegen/csharp/verification/_generate.py, aas_core_codegen/parse/_rules.py, aas_core_codegen/parse/tree.py
Since we do not have a clear use case yet for
`ExpressionWithDeclarations` (and consequently for `Declaration`), we
remove these two classes from *our* internal abstract syntax tree.
Additionally, there were breaking changes between Python 3.8 and 3.9
which have repercussions on parsing indices (and hence how we get to
`ExpressionWithDeclarations`). At this moment, we decide not to support
the concept and avoid the additional implementation complexity.
Once and if we have a clear use case, we will add these two classes
back into the parse tree.
=> Remove `ExpressionWithDeclarations` from our tree

.github/workflows/ci.yml, .gitignore, .idea/aas-core-csharp-codegen.iml, aas_core_codegen/parse/_translate.py, setup.py, tests/test_parse.py
Previously, we only supported Python 3.8. Since there were breaking
changes in the `ast` module of Python 3.9, we have to switch on the
Python version and adapt the parsing accordingly.
=> Add support for Python 3.9

CHANGELOG.rst, aas_core_codegen/__init__.py, setup.py
* Add support for Python 3.10 (#27)
* Add support for Python 3.9 (#26)
* Remove ``ExpressionWithDeclarations`` from our tree (#25)
* Revert lost `--version` command flag (#23)
=> Release 0.0.3

continuous_integration/precommit.py, setup.py
This patch upgrade the black to the latest version since we faced
various black-related bugs. We hope that the new version will be able to
fix them.
=> Upgrade black to 22.1.0

continuous_integration/check_help_in_readme.py, continuous_integration/check_init_and_setup_coincide.py, continuous_integration/precommit.py, tests/common.py, tests/csharp/live_test_main.py, tests/csharp/test_common.py, tests/csharp/test_description.py, tests/csharp/test_main.py, tests/infer_for_schema/test_len_on_properties.py, tests/infer_for_schema/test_len_on_self.py, tests/infer_for_schema/test_patterns_on_properties.py, tests/infer_for_schema/test_patterns_on_self.py, tests/intermediate/test_constructor.py, tests/intermediate/test_hierarchy.py, tests/intermediate/test_translate.py, tests/jsonschema/test_main.py, tests/test_parse.py
We excluded the test and continuous integration code from pylint checks
since we did not really care about most of the rules. However, if
there is a ``TODO`` in the tests, there is no check to actually detect
it. There were already multiple cases where we checked in ``TODO`` code
inadvertently.
Therefore we add the test code in pylint check in this patch.
This patch also includes all the fixes which were necessary to make
pylint happy.
=> Include test and CI code in pylint precommit check

aas_core_codegen/csharp/verification/_generate.py, aas_core_codegen/intermediate/_types.py, aas_core_codegen/intermediate/type_inference.py, tests/intermediate/test_type_inference.py
Currently, we do not consider the broader scope of an environment and
miss to de-reference enumerations and, consequently, enumeration
literals. This patch:
* encapsulates the logic for populating the global scope into
an environment,
* encapsulates the logic for inferring the types of the node tree of an
invariant, and
* tests this in isolation.
=> Infer type of enumeration literals in invariants

aas_core_codegen/csharp/verification/_generate.py, test_data/csharp/test_main/v3rc2/expected_output/verification.cs
There was a minor bug where double curly brackets were written in a code
block, but the string literal has not been interpolated.
The bug went unnoticed since we did not re-run live test on C#.
=> Fix double curly brackets in C# verification

aas_core_codegen/csharp/jsonization/_generate.py, aas_core_codegen/intermediate/__init__.py, aas_core_codegen/intermediate/_types.py, test_data/csharp/test_main/v3rc2/expected_output/jsonization.cs, tests/csharp/live_test_main.py
The current meta-model does not allow for one-pass deserialization, so
we have to revert to two-pass deserialization.
=> Make jsonization in C# two-pass

test_data/jsonschema/test_main/v3rc1/expected_output/schema.json, test_data/jsonschema/test_main/v3rc1/expected_output/stdout.txt, test_data/jsonschema/test_main/v3rc1/input/meta_model.py, test_data/jsonschema/test_main/v3rc1/input/snippets/Lang_string_set.json, test_data/jsonschema/test_main/v3rc1/input/snippets/schema_base.json
Currently, we only used version V3RC02 of the meta-model for testing the
generation of JSON schema. With this patch, we add V3RC01 to the test
suite as well.
=> Add V3RC01 in test data for JSON schema

test_data/jsonschema/test_main/v3rc1/expected_output/schema.json, test_data/jsonschema/test_main/v3rc1/input/meta_model.py, test_data/jsonschema/test_main/v3rc1/input/snippets/Value_data_type.json
This patch introduces the `ValueDataType` into the test case of JSON
Schema based on the meta-model version V3RC01.
=> Add `ValueDataType` in JSON schema test for V3RC01

requirements.txt
We have to lift the minimum docutils version to 0.18.1 since we use some
of its novel features (*e.g.*, `findall`) which are not available in the
current docutils version 0.17.1.
The problem went unnoticed since we always installed the newest version
locally, and became only apparent when the lowest version had been
installed.
Fixes #42.
=> Upgrade docutils to 0.18.1

aas_core_codegen/csharp/verification/_generate.py
There was a spot where we forgot to erase the reference to
`RefAnnotationType` which was removed from the intermediate
representation in #39.
=> Fix outdated comment in C# generator

test_data/jsonschema/test_main/v3rc1/expected_output/schema.json, test_data/jsonschema/test_main/v3rc1/input/meta_model.py, test_data/jsonschema/test_main/v3rc1/input/snippets/Value_data_type.json
We currently do not handle `ValueDataType` as a special type, but
consider it simply a string.
With this patch, we remove `Value_data_type` from the tests for JSON
schema and equalize the meta-models for RDF and JSON Schema tests.
=> Remove `Value_data_type` from JSONSchema tests

CHANGELOG.rst, aas_core_codegen/__init__.py, setup.py
* Approximate RDF to aas-specs (#49)
* Fix RDF schema generation (#48)
* Generte RDF and SHACL schemas (#46)
* Introduce topologically sorted symbols in the table (#45)
* Upgrade docutils to 0.18.1 (#43)
* Remove `RefTypeAnnotation` from the IR (#39)
* Make jsonization in C# two-pass (#37)
* Fix double curly brackets in C# verification (#36)
* Infer type of enumeration literals in invariants (#32)
* Allow enumeration literals to be arbitrary strings (#31)
=> Release 0.0.4

aas_core_codegen/jsonschema/main.py, aas_core_codegen/naming.py, test_data/csharp/test_main/v3rc2/expected_output/jsonization.cs, test_data/jsonschema/test_main/v3rc1/expected_output/schema.json, test_data/jsonschema/test_main/v3rc2/expected_output/schema.json, tests/jsonschema/test_main.py
We always introduced an `allOf` even though there is a single
definition. With this patch, we check for the number of possible
definitions and, if there is only one, write the properties directly in
the definition.
Additionally, we fix the naming to coincide more with the official JSON
schema in the http://github.com/admin-shell-io/aas-specs.
=> Approximate naming and `allOf` to aas-specs JSON

aas_core_codegen/jsonschema/main.py, test_data/jsonschema/test_main/v3rc1/expected_output/schema.json, test_data/jsonschema/test_main/v3rc2/expected_output/schema.json
Currently we always include the `type` property even though a definition
"inherits" from another definition through `allOf`.
With this patch, the `type` property is only defined if there are no
ancestor definitions.
=> Remove redundant `type` property in JSON schema

aas_core_codegen/jsonschema/main.py, test_data/jsonschema/test_main/v3rc1/expected_output/schema.json, test_data/jsonschema/test_main/v3rc1/input/meta_model.py, test_data/jsonschema/test_main/v3rc2/expected_output/schema.json
We add the discrimantor property `modelType`, conforming to the official
specs in admin-shell-io aas-specs repository.
=> Add `modelType` in JSON schema

aas_core_codegen/jsonschema/main.py, test_data/jsonschema/test_main/v3rc1/expected_output/schema.json, test_data/jsonschema/test_main/v3rc2/expected_output/schema.json
The qualifier `anyOf` is too restrictive for abstract classes since we
want to reject overlapping properties.
=> Use `oneOf` instead of `anyOf` in JSON schema

aas_core_codegen/intermediate/__init__.py, aas_core_codegen/intermediate/_translate.py, aas_core_codegen/intermediate/_types.py, aas_core_codegen/jsonschema/main.py
We erroneously called the function
`collect_ids_of_classes_in_properties`, while we actually collected the
IDs of the symbols.
=> Fix naming for set of symbols used in properties

aas_core_codegen/jsonschema/main.py, test_data/jsonschema/test_main/v3rc1/expected_output/schema.json, test_data/jsonschema/test_main/v3rc2/expected_output/schema.json
With this patch, we omit to generate the code for all the symbols which
are not used in any of the properties of any of the classes.
=> Skip unused symbols in JSON schema

test_data/jsonschema/test_main/v3rc1/expected_output/schema.json, test_data/jsonschema/test_main/v3rc1/input/meta_model.py, test_data/rdf_shacl/test_main/v3rc1/expected_output/rdf-ontology.ttl, test_data/rdf_shacl/test_main/v3rc1/expected_output/shacl-schema.ttl, test_data/rdf_shacl/test_main/v3rc1/input/meta_model.py
We change `values` to `value` in `SubmodelElementCollection`. See [this
comment].
[this comment]: https://github.com/admin-shell-io/aas-specs/pull/98#discussion_r809116327
=> Update test data for V3RC01 after JSON review

aas_core_codegen/parse/_translate.py, test_data/parse/unexpected/class_decorators/non_name_decorator/expected_error.txt
We change the order of parsing functions and introduce a union to
abstract a general class decorators. To make parsing of novel decorators
easier, we additionally introduce a dispatch function so that there is a
single point of entry for class decorators.
=> Refactor parsing of decorators for extensibility

aas_core_codegen/csharp/description.py, aas_core_codegen/intermediate/_translate.py, aas_core_codegen/intermediate/doc.py, aas_core_codegen/intermediate/rendering.py, aas_core_codegen/rdf_shacl/_description.py, test_data/csharp/test_main/v3rc2/input/meta_model.py, test_data/intermediate/expected/real_meta_models/v3rc2/meta_model.py, test_data/jsonschema/test_main/v3rc2/input/meta_model.py, test_data/parse/expected/real_meta_models/v3rc2/meta_model.py, tests/intermediate/test_translate.py
We introduce a special role, `constraintref`, to indicate references to
constraints. In a future pull request, we will introduce handling of the
constraints as field lists.
=> Introduce `constraintref` role in the docs

test_data/csharp/test_main/v3rc2/expected_output/types.cs, test_data/csharp/test_main/v3rc2/input/meta_model.py, test_data/intermediate/expected/real_meta_models/v3rc2/meta_model.py, test_data/jsonschema/test_main/v3rc1/input/meta_model.py, test_data/jsonschema/test_main/v3rc2/input/meta_model.py, test_data/parse/expected/real_meta_models/v3rc2/meta_model.py, test_data/rdf_shacl/test_main/v3rc1/expected_output/rdf-ontology.ttl, test_data/rdf_shacl/test_main/v3rc1/input/meta_model.py
We sync with aas-core-meta and add `:constraintref:` to all test
meta-models to reflect the references to constraints.
=> Add `:constraintref:` to all meta-models

aas_core_codegen/infer_for_schema/__init__.py, aas_core_codegen/infer_for_schema/_inline.py, aas_core_codegen/infer_for_schema/_len.py, aas_core_codegen/infer_for_schema/_pattern.py, aas_core_codegen/intermediate/__init__.py, aas_core_codegen/intermediate/_types.py, aas_core_codegen/jsonschema/main.py, aas_core_codegen/rdf_shacl/common.py, aas_core_codegen/rdf_shacl/rdf.py, aas_core_codegen/rdf_shacl/shacl.py, test_data/jsonschema/test_main/v3rc1/expected_output/schema.json, test_data/jsonschema/test_main/v3rc2/expected_output/schema.json, tests/infer_for_schema/test_len_on_properties.py, tests/infer_for_schema/test_len_on_self.py, tests/infer_for_schema/test_patterns_on_properties.py, tests/infer_for_schema/test_patterns_on_self.py
Since the JSON schema is going to be also used for OpenAPI 3 schema, we
should not introduce additional definitions. Therefore we in-line the
constraints of constrained primitives in the actual properties of the
objects.
This change also had repercussions on SHACL generation as we in-line
the constrained primitives there as well.
=> In-line constrained primitives in JSON Schema

aas_core_codegen/jsonschema/main.py, test_data/jsonschema/test_main/v3rc1/expected_output/schema.json, test_data/jsonschema/test_main/v3rc2/expected_output/schema.json
We need to remove the `*_abstract` definitions which specified the
"closed world" with `oneOf` since the generated JSON schema is also used
for various downstream code generations (*e.g.*, in OpenAPI 3 schemas
and respective server generations).
=> Remove `*_abstract` definitions from JSON

aas_core_codegen/intermediate/_translate.py, aas_core_codegen/jsonschema/main.py, aas_core_codegen/parse/_translate.py, test_data/jsonschema/test_main/v3rc1/expected_output/schema.json, test_data/jsonschema/test_main/v3rc2/expected_output/schema.json
Instead of automatically inferring `modelType` in serialization, which
was error prone and succeptible to changes between meta-model versions,
we use serialization settings to determine the enumeration `ModelTypes`
in JSON schema.
=> Fix `ModelTypes` enumeration in JSON

continuous_integration/precommit.py, dev_scripts/__init__.py, dev_scripts/fetch_meta_models_from_aas_core_meta.py, dev_scripts/run_tests_with_rerecord.py, setup.py, tests/csharp/test_main.py, tests/intermediate/test_translate.py, tests/jsonschema/test_main.py, tests/rdf_shacl/test_main.py, tests/test_parse.py
We write multiple scripts to facilitate back-propagation of changes from
the aas-core-meta repository to our test data.
=> Add scripts for propagation from aas-core-meta

CONTRIBUTING.rst
We mention `dev_scripts` in `CONTRIBUTING.rst` so that other developers
are aware of their existence.
=> Document `dev_scripts`

CONTRIBUTING.rst
We erroneously wrote markdown instead of ReST.
=> Fix links related to `dev_scripts` in the docs

aas_core_codegen/csharp/verification/_generate.py, test_data/csharp/test_main/v3rc2/expected_output/verification.cs
We add a remark to warn the users of the code that passing paths around
is expensive. Hopefully we will be notified when this becomes a problem.
Otherwise, if the time permits at the end we plan to come back and
optimize the error handling so that we avoid this cost.
=> Document the bottleneck in C# verification

.idea/dictionaries/rist.xml, aas_core_codegen/csharp/jsonization/_generate.py, test_data/csharp/test_main/v3rc2/expected_output/jsonization.cs, test_data/csharp/test_main/v3rc2/input/snippets/Jsonization/Lang_string_set_from.cs
Currently, we pass in the path on every call to a deserialization
method. This is problematic since this induces a time complexity
of `O(n^2)` with `n` being the maximum length of a path. We need to
append the suffix on each call and therefore make a complete copy of the
previous path (the strings are stored as blocks in memory akin to arrays
in C#).
With this patch, we use an intermediate structure (`Error`) which stores
the path as a linked list. We append to this linked list when we unwind
the calls so that the time complexity is brought down to `O(n)`.
Additionally, the suffixes are appended only in case of errors which
should yield even better performance assuming that the correct data is
usually much more probable than incorrect data.
=> Optimize path handling in C# JSON deserialization

tests/csharp/live_test_main.py
This was an unintentional omission.
=> Undo debugging code in C# live test

aas_core_codegen/csharp/verification/_generate.py, aas_core_codegen/intermediate/type_inference.py, aas_core_codegen/parse/_rules.py, aas_core_codegen/parse/tree.py, test_data/csharp/test_main/v3rc2/expected_output/jsonization.cs, test_data/csharp/test_main/v3rc2/expected_output/types.cs, test_data/csharp/test_main/v3rc2/expected_output/verification.cs, test_data/csharp/test_main/v3rc2/input/meta_model.py, test_data/csharp/test_main/v3rc2/input/snippets/Verification/is_model_reference_to.cs, test_data/intermediate/expected/real_meta_models/v3rc2/expected_symbol_table.txt, test_data/intermediate/expected/real_meta_models/v3rc2/meta_model.py, test_data/jsonschema/test_main/v3rc2/expected_output/schema.json, test_data/jsonschema/test_main/v3rc2/input/meta_model.py, test_data/parse/expected/real_meta_models/v3rc2/expected_symbol_table.txt, test_data/parse/expected/real_meta_models/v3rc2/meta_model.py
We add support for `all` built-in as well as simple generator
expressions in the intermediate representation.
=> Handle `all` in intermediate representation

aas_core_codegen/intermediate/_translate.py, aas_core_codegen/intermediate/_types.py, test_data/csharp/test_main/v3rc2/expected_output/jsonization.cs, test_data/csharp/test_main/v3rc2/expected_output/types.cs, test_data/csharp/test_main/v3rc2/expected_output/verification.cs, test_data/intermediate/expected/class/inheritance/expected_symbol_table.txt, test_data/intermediate/expected/interface/inheritance/expected_symbol_table.txt, test_data/intermediate/expected/real_meta_models/v3rc2/expected_symbol_table.txt
We refactor `intermediate.translate` in a major way such that the
heritage of the classes and constrained primitives is stacked only in
the second passes. The benefits are the following:
+ The code is easier to read. Instead of hacking around with the `parse`
representation, we can use resolved references to parents.
+ We were re-parsing the properties and methods in the classes from the
ancestors simply because we could not access them due to inappropriate
representation. This makes the reporting of errors convoluted as we
would have to re-report the errors on every inherited property or
method. With this change, we parse the properties and methods only
once and report the errors correctly.
However, this refactoring has one big drawback, which we still found
acceptable:
- The state of …
=> Stack heritage in second passes

aas_core_codegen/intermediate/_translate.py
We move out the translation of the meta-model information in
`intermediate._translate` to a separate function so that we can trace
the changes to this particular piece of logic more easily.
This will also make adding errors in the upcoming changes nicer to
trace.
=> Refactor translation of meta-model information

dev_scripts/run_tests_with_rerecord.py
During a debugging session it is helpful if we do not waste time
re-rendering all the outputs in the test data, but only a subset that we
are actively developing.
This change introduces a `--select` parameter to that end in the
`run_tests_with_rerecord.py` script.
=> Allow selection in rerendering dev script

aas_core_codegen/intermediate/_translate.py, test_data/csharp/test_main/v3rc2/expected_output/jsonization.cs, test_data/csharp/test_main/v3rc2/expected_output/types.cs, test_data/csharp/test_main/v3rc2/input/meta_model.py, test_data/intermediate/expected/real_meta_models/v3rc2/expected_symbol_table.txt, test_data/intermediate/expected/real_meta_models/v3rc2/meta_model.py, test_data/intermediate/unexpected/properties_and_constructor_arguments_do_not_match/after_inheritance/expected_error.txt, test_data/intermediate/unexpected/properties_and_constructor_arguments_do_not_match/after_inheritance/meta_model.py, test_data/intermediate/unexpected/properties_and_constructor_arguments_do_not_match/within_class/expected_error.txt, test_data/intermediate/unexpected/properties_and_constructor_arguments_do_not_match/within_class/meta_model.py, test_data/jsonschema/test_main/v3rc1/input/meta_model.py, test_data/jsonschema/test_main/v3rc2/input/meta_model.py, test_data/parse/expected/real_meta_models/v3rc2/expected_symbol_table.txt, test_data/parse/expected/real_meta_models/v3rc2/meta_model.py, test_data/rdf_shacl/test_main/v3rc1/input/meta_model.py
We verify that the order of the properties and the order of the
constructor arguments is consistent. We match them simply by names and
do not analyze the code any further.
We hope that this makes the meta-model more consistent and thus easier
to read.
=> Check the order of properties and constructor args

aas_core_codegen/parse/_translate.py, test_data/parse/unexpected/enum/non_assignment/expected_error.txt
When we parse an enumeration and there were errors, they were not
conclusive enough. We try to improve them with necessary details in this
patch.
=> Produce better errors on unexpected enum elements

aas_core_codegen/parse/_translate.py, test_data/parse/unexpected/enum/non_assignment/expected_error.txt
We have to exclude the type of the problematic `ast` nodes from the
errors since they differ between Python versions. This makes:
1) testing a bit harder (as we'd have to have different test data
*per Python version*), and
2) reporting errors would be confusing if the user and the developer
have different Python versions.
=> Exclude `ast` class names from errors

continuous_integration/check_test_meta_models_coincide.py, continuous_integration/precommit.py, dev_scripts/sync_meta_model.py
We group the test meta-models by version and enforce that they coincide
within the same group. However, we often develop the code and *change*
a meta-model at the same time. Once we are done with the development, we
had to tediously sync the meta-models within the group by hand.
In this change, we write a script to automate this syncing in order to
speed the development process.
=> Script syncing of the test meta-models

CHANGELOG.rst, aas_core_codegen/__init__.py, setup.py
* Infer schema constraints only for strings (#115)
* Return errors instead of raising in C# jsonization (#114)
* Exclude ``ast`` class names from errors (#112)
* Produce better errors on unexpected enum elements (#111)
* Check the order of properties and constructor args (#107)
* Extract structure information from docstrings (#106)
* Handle ``all`` in intermediate representation (#95)
* Introduce ``constraintref`` role in the docs (#71)
* Parse ``reference_in_the_book`` (#69)
* Remove ``ID`` from abbreviations in ``naming`` (#60)
* Fix naming for set of symbols used in properties (#57)
C#
--
* Refactor verification in ``IEnumerable`` in C# (#93)
* Refactor errors to ``Reporting`` in C# (#92)
* Generate JSON paths for C# jsonization errors (#91)
* Optimize path handling in C# JSON …
=> Release 0.0.5

aas_core_codegen/infer_for_schema/_inline.py, aas_core_codegen/infer_for_schema/_len.py
We had an indentation error in a loop so the reporting of errors was
always skipped in `infer_for_schema` for length constraints.
=> Fix swallowed errors in `infer_for_schema`

tests/smoke/test_main.py
We mistakenly merged a TODO in the module `tests.smoke` since it lacked
the `__init__.py` marker in the directory and was thus omitted by
pylint.
=> Remove a TODO from `tests.smoke`

tests/smoke/test_main.py
For some reason, pylint forgot to warn us about the missing disables in
the `tests.smoke` and we hastly merged in the changes.
=> Add pylint disables in `tests.smoke`

aas_core_codegen/csharp/description.py, aas_core_codegen/intermediate/_translate.py
We mistakenly omitted property constraints when we iterated over the
description elements. This resulted in unresolved attribute references.
=> Include constraints in description iterations

.idea/dictionaries/rist.xml, aas_core_codegen/intermediate/_types.py, aas_core_codegen/parse/_translate.py, aas_core_codegen/xsd/main.py, aas_core_codegen/xsd/naming.py, test_data/xsd/test_main/v3rc2/expected_output/schema.xml, test_data/xsd/test_main/v3rc2/input/snippets/root_element.xml
We did not really handle the interfaces (abstract classes or concrete
classes with one or more concrete descendants). With this change, we
represent them as choices of possible elements.
=> Fix interfaces in XSD

test_data/xsd/test_main/v3rc2/expected_output/schema.xml, test_data/xsd/test_main/v3rc2/input/snippets/root_element.xml
We fix the snippet in the test data to use the appropriate type for the
environment (`environment_t`). Previously, we mistakenly took the type
from V3RC01, `assetAdministrationShellEnvironment_t`.
=> Fix XSD to use correct environment type

aas_core_codegen/xsd/main.py, test_data/xsd/test_main/v3rc2/expected_output/schema.xml, tests/xsd/test_main.py
Many schema validators do not handle special escape characters `\x??` in
`xs:pattern` correctly, we have to undo the escaping in the patterns
and put them in `xs:pattern` in their original unicode characters.
=> Undo escaping of `\x??` in XSD

aas_core_codegen/intermediate/_translate.py, aas_core_codegen/intermediate/_types.py
We add a note in the types of the intermediate representation why the
pre-conditions of a method are not modeled in the disjunctive normal
form which is common for programming languages supporting contracts.
Namely, we do not handle overriding of the methods at the moment, so we
leave this change in the intermediate representation for the future. The
note was however necessary to avoid confusion.
=> Remark why pre-conditions are not conjunctions

aas_core_codegen/parse/tree.py
We forgot to include ``original_node`` in the stringification by
mistake.
=> Fix stringify of ``parse.tree.IsNone``

aas_core_codegen/csharp/verification/_generate.py
We mistakenly used ``repr`` to represent string literals in invariants.
With this patch, we correctly render the constant as a proper C# string
literal.
=> Represent string constants as literals in C#

aas_core_codegen/csharp/verification/_generate.py
We mistakenly used ``textwrap.dedent`` which fails when one of the
string interpolations consists of multiple lines.
With this patch, we fix the issue by avoiding ``textwrap.dedent`` and
using a vanilla string literal.
=> Fix formatting of multi-line invariants in C#

aas_core_codegen/csharp/verification/_generate.py, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/verification.cs
This change is a rudimentary heuristic to break long conditions into
much more readable multiple lines.
=> Break lines on invariants in C#

aas_core_codegen/csharp/verification/_generate.py, aas_core_codegen/infer_for_schema/_inline.py, aas_core_codegen/infer_for_schema/_len.py, aas_core_codegen/intermediate/_types.py
I had an error in my live template where the day of the note was written
without a preceding zero in the days.
This patch makes the note comments uniform again.
=> Fix `NOTE` comments

aas_core_codegen/intermediate/_translate.py, test_data/intermediate/unexpected/documentation/unexpected_documentation_elements/expected_error.txt, test_data/intermediate/unexpected/documentation/unexpected_documentation_elements/meta_model.py
We introduce an additional verification at the intermediate stage to
check that all documentation elements can be rendered using a dummy
smoke renderer. This is necessary since we had bad suprises over at
aas-core-meta, so we want to catch these issues as soon as possible.
=> Render the descriptions with smoke at intermediate

aas_core_codegen/xsd/main.py, test_data/xsd/test_main/aas_core_meta.v3rc2/expected_output/schema.xsd
We group the children of the ``<schema>`` by their tag and then sort by
``name`` attribute within the group.
This makes it easier to:
* diff,
* search, and
* compare against JSON Schema and RDF+SHACL.
=> Sort schema elements by tag and name in XSD

aas_core_codegen/csharp/visitation/_generate.py, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/visitation.cs
With this change, we provide a practical set of visitors in
``visitation.cs`` in C#.
Previously, we did not have a practical use case for the visitors.
Now we implemented xmlization (coming in the future patch), and so
figured out what kind of visitors were still missing.
=> Implement a practical set of visitors in C#

aas_core_codegen/csharp/stringification/_generate.py, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/stringification.cs
Since we are going to return a nullable string anyhow, we accept just as
well nullable enum literals. This makes the client code a bit easier to
manage.
Additionally, C# is kind of peculiar about nullable value types. See
this StackOverflow answer for more information: [1].
[1]: https://stackoverflow.com/questions/54593923/nullable-reference-types-with-generic-return-type/54594285#54594285
=> Allow null enums in C# stringification

aas_core_codegen/csharp/jsonization/_generate.py
We missed an unused argument (related to implementation-specific
snippets). Removing it simplified the code a bit.
=> Remove unused arguments in C# jsonization

aas_core_codegen/csharp/jsonization/_generate.py
We add a segment in the middle of the key to make it more explicit to
which class in the de/serialization Uberclass the snippets will belong
to. This makes it easier for the reader of the snippets to follow where
they are going to be inserted.
=> Specify more implementation keys in C# jsonization

aas_core_codegen/csharp/jsonization/_generate.py, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/jsonization.cs
We fix the documentation comment and replace "entities" with "classes"
to avoid confusing the reader. There is indeed a meta-model class
"Entity", so this can be indeed misleading.
=> Fix documentation about classes in C# jsonization

aas_core_codegen/csharp/jsonization/_generate.py, aas_core_codegen/intermediate/_translate.py, test_data/intermediate/expected/type_annotation/subscripted/expected_symbol_table.txt, test_data/intermediate/expected/type_annotation/subscripted/meta_model.py
We check at the intermediate stage that only a limited set of type
annotation patterns is used. This greately simplifies the generators.
However, we anticipate that more complex type patterns are going to be
used in the meta-models in the future. At the moment, we stick to the
simple generators, and explicitly check for these simplifying
assumptions.
=> Verify the limitedness of type annotations

.gitignore, aas_core_codegen/rdf_shacl/rdf.py, test_data/rdf_shacl/test_main/aas_core_meta.v3rc1/expected_output/rdf-ontology.ttl, test_data/rdf_shacl/test_main/aas_core_meta.v3rc2/expected_output/rdf-ontology.ttl, test_data/rdf_shacl/test_main/aas_core_meta.v3rc2/expected_output/shacl-schema.ttl, test_data/rdf_shacl/test_main/aas_core_meta.v3rc2/expected_output/stdout.txt, test_data/rdf_shacl/test_main/aas_core_meta.v3rc2/input/snippets/rdf/preamble.ttl, test_data/rdf_shacl/test_main/aas_core_meta.v3rc2/input/snippets/shacl/preamble.ttl, test_data/rdf_shacl/test_main/aas_core_meta.v3rc2/input/snippets/url_prefix.txt, tests/rdf_shacl/test_main.py
We make changes to RDF and SHACL generation so that our generated
schemas are as similar as possible to the schemas in
admin-shell-io/aas-specs repository for the version V3RC02 on the branch
[feature/rdf/updateToV3.0RC02].
[feature/rdf/updateToV3.0RC02]: https://github.com/admin-shell-io/aas-specs/tree/feature/rdf/updateToV3.0RC02
=> Adapt RDF and SHACL to match aas-specs V3RC02

requirements-dev.txt, setup.py
We refactor the development requirements (*i.e.*, dependencies) into a
separate text file, ``requirements-dev.txt``, to be consistent with
``requirements.txt``.
=> Refactor dev requirements into a txt file

aas_core_codegen/csharp/structure/_generate.py, aas_core_codegen/csharp/visitation/_generate.py
At a couple of spots we did not specify the indentions in C# code
generations, but just left four spaces in the templates (``    ``).
We replace the indentions with the explicit snippet (``{I}``, ``{II}``
*etc.*).
=> Fix unspecified indentions in C#

aas_core_codegen/csharp/jsonization/_generate.py, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/jsonization.cs
There was a bug related to ``textwrap.dedent`` where we start the
template with an indention (``{I}``) which is later "eaten" by
``textwrap.dedent``.
We remove ``textwrap.dedent`` for these cases so that the formatting in
the generated code becomes correct.
=> Fix indention in snippets of C# jsonization

.gitignore, .idea/dictionaries/rist.xml, aas_core_codegen/intermediate/_types.py, tests/intermediate/test_types.py
We introduce a function to check for subclassing between two classes in
the intermediate layer to simplify the life of the downstream clients.
=> Allow for subclass checks in intermediate

aas_core_codegen/stringify.py, test_data/intermediate/expected/class/inheritance/expected_symbol_table.txt, test_data/intermediate/expected/class/methods_with_contracts/expected_symbol_table.txt, test_data/intermediate/expected/class/only_property_no_method/expected_symbol_table.txt, test_data/intermediate/expected/interface/basic/expected_symbol_table.txt, test_data/intermediate/expected/interface/inheritance/expected_symbol_table.txt, test_data/intermediate/expected/interface/method_signature/expected_symbol_table.txt, test_data/intermediate/expected/interface/only_constructor/expected_symbol_table.txt, test_data/intermediate/expected/type_annotation/atomic/expected_symbol_table.txt, test_data/intermediate/expected/type_annotation/subscripted/expected_symbol_table.txt, test_data/intermediate/real_meta_models/aas_core_meta.v3rc2/expected_symbol_table.txt, test_data/parse/expected/method/contracts/multiple_contracts_in_order/expected_symbol_table.txt, test_data/parse/expected/method/contracts/postcondition/snapshot/with_keyword_arguments/expected_symbol_table.txt, test_data/parse/expected/method/contracts/postcondition/snapshot/with_positional_arguments/expected_symbol_table.txt, test_data/parse/real_meta_models/aas_core_meta.v3rc2/expected_symbol_table.txt
Currently, stringify outputs a single-line string representation of
text. This makes it very hard to diff test data against changes when we
manually need to inspect it.
Hence we render the multi-line text in the stringified test data as
multi-line string literals to make the diffing easier for the developer.
=> Make stringify output multi-line string

aas_core_codegen/infer_for_schema/__init__.py, aas_core_codegen/infer_for_schema/_inline.py, aas_core_codegen/infer_for_schema/_len.py, aas_core_codegen/infer_for_schema/_pattern.py, aas_core_codegen/infer_for_schema/_stringify.py, aas_core_codegen/infer_for_schema/_types.py, aas_core_codegen/stringify.py, test_data/xsd/test_main/aas_core_meta.v3rc2/expected_output/schema.xsd, tests/infer_for_schema/common.py, tests/infer_for_schema/test_len_on_properties.py, tests/infer_for_schema/test_len_on_self.py, tests/infer_for_schema/test_patterns_on_properties.py, tests/infer_for_schema/test_patterns_on_self.py
We infer the schema constraints (currently only length and patterns)
based on the meta-model. We do not inherit them by default since we
usually generate the invariants for each class in the schema
*separately* and let the schema engine deal with the inheritance.
However, in the case of test data generation, it would be helpful if the
schema constraints are properly inherited among the classes.
In this patch, we re-structure the code and the tests to cater for that
use case and extend the logic with an additional function to stack the
schema constraints by the class ontology.
Unsurprisingly, a couple of bugs were discovered and fixed along
the re-structuring.
=> Fix stacking of inferred schema constraints

aas_core_codegen/intermediate/_translate.py
Since the implementation-specific methods are going to be manually
written and the contracts need not be transpiled, we allow the contracts
in the intermediate stage.
=> Allow contracts for impl.-specific methods

aas_core_codegen/csharp/structure/_generate.py
We move all the snippets for methods and classes in C# to a separate
directory to make the browsing of the snippets a bit easier for the
developer.
=> Expect C# snippets for types in a directory

aas_core_codegen/csharp/structure/_generate.py, aas_core_codegen/intermediate/_stringify.py, aas_core_codegen/intermediate/_translate.py, aas_core_codegen/intermediate/_types.py, test_data/csharp/test_main/aas_core_meta.v3rc2/input/snippets/Types/Concept_description/category_or_default.cs, test_data/csharp/test_main/aas_core_meta.v3rc2/input/snippets/Types/Extension/value_type_or_default.cs, test_data/intermediate/expected/class/implementation_specific_method/expected_symbol_table.txt, test_data/intermediate/expected/class/inheritance/expected_symbol_table.txt, test_data/intermediate/expected/class/methods_with_contracts/expected_symbol_table.txt, test_data/intermediate/expected/class/only_method_no_property/expected_symbol_table.txt, test_data/intermediate/expected/interface/basic/expected_symbol_table.txt, test_data/intermediate/expected/interface/inheritance/expected_symbol_table.txt, test_data/intermediate/expected/interface/method_signature/expected_symbol_table.txt
Since the methods are inherited, we need to introduce `specified_for`
in the intermediate representation so that we do not re-generate the
same method in the descendant classes.
=> Introduce `specified_for` for methods

aas_core_codegen/csharp/structure/_generate.py, aas_core_codegen/intermediate/_types.py, test_data/intermediate/expected/class/inheritance/expected_symbol_table.txt, test_data/intermediate/expected/interface/inheritance/expected_symbol_table.txt
We re-visited how the methods are inherited and interfaces are
generated, and discovered a couple of subtle bugs related to
how we ignored `specified_for` of a method during the translation stage
to intermediate.
=> Re-visit inheritance of methods and signatures

.idea/aas-core-csharp-codegen.iml, aas_core_codegen/csharp/verification/_generate.py, aas_core_codegen/intermediate/type_inference.py, aas_core_codegen/parse/_rules.py, aas_core_codegen/parse/tree.py
We did not thouroughly test the transpilation of ``any`` in invariants,
but add it to our parsing. This is necessary since we need to create a
new version of aas-core-meta which uses ``any`` in some of the
invariants and the smoke tests fail at the moment.
Non-experimental support and testing is coming in one of the upcoming
commits.
=> Add experimental support for ``any`` in invariants

.idea/dictionaries/rist.xml, CHANGELOG.rst, aas_core_codegen/__init__.py, setup.py
* Verify the limitedness of type annotations (#156)
* Allow for subclass checks in intermediate (#164)
* Make stringify output multi-line string (#165)
* Fix stacking of inferred schema constraints (#166)
* Fix methods ignored in intermediate (#167)
* Allow contracts for impl.-specific methods (#168)
* Introduce ``specified_for`` for methods (#170)
* Re-visit inheritance of methods and signatures (#171)
* Add experimental support for ``any`` in invariants (#173)
C#
--
* Implement a practical set of visitors in C# (#151)
* Allow null enums in C# stringification (#152)
* Remove unused arguments in C# jsonization (#153)
* Specify more implementation keys in C# jsonization (#154)
* Fix documentation about classes in C# jsonization (#155)
* Write xmlization for C# (#157)
* Fix unspecified …
=> Release 0.0.9

aas_core_codegen/xsd/main.py, test_data/xsd/test_main/aas_core_meta.v3rc2/examples/expected/submodels/property/property_with_id_short.xml
In cases where an abstract class is defined in the meta-model, but no
implementers are provided, we generated an invalid XSD. Namely, we
expected a choice group to exist, but since there were no implementers,
no choice group has been generated.
In this patch, we generate an empty element for the abstract class and
simply refer to it instead of the choice.
We manually tested against aas-core-meta 2022.5.26. Therefore we also
update the example to comply with this newer meta-model despite the fact
that the repository still uses aas-core-meta 2022.5.30a6 for testing.
We will update to the latest aas-core-meta 2022.5.26 very soon in one of
the upcoming commits.
=> Fix XSD for abstract classes without implementers

aas_core_codegen/rdf_shacl/shacl.py, test_data/rdf_shacl/test_main/aas_core_meta.v3rc1/expected_output/shacl-schema.ttl, test_data/rdf_shacl/test_main/aas_core_meta.v3rc2/expected_output/shacl-schema.ttl
There was a typo in the generated RDF schema which has been introduced
by copy/pasting from the original RDF schema which we used as a
template.
=> Fix a typo in RDF query message

aas_core_codegen/stringify.py
We modify the assertions in the ``stringify`` module to exclude classes
coming from outside of the ``_types`` module. This is not only more
efficient, but also makes the debugging easier.
=> Exclude external classes stringify assertions

tests/common.py, tests/csharp/test_main.py, tests/csharp/test_verification.py, tests/intermediate/test_translate.py, tests/our_jsonschema/test_main.py, tests/parse/test_parse.py, tests/parse/test_retree.py, tests/rdf_shacl/test_main.py, tests/smoke/test_main.py, tests/xsd/test_main.py
We refactor the environment variable in the common module since now many
tests depend on it. Originally, only a few tests were using it, so there
was no need to encapsulate it in one place.
=> Refactor ``RERECORD`` into ``tests.common``

aas_core_codegen/infer_for_schema/_inline.py, aas_core_codegen/infer_for_schema/_types.py, tests/infer_for_schema/test_patterns_on_properties.py
In cases where a property is a constrained primitive, the stacking of
pattern constraint over ancestor is broken, as we inherit the
constraints multiple times.
As we do not keep track of where the constraints of the ancestors come
from, we simply de-duplicate by keeping a set of observed patterns.
=> Fix duplicate inheritance of pattern constraints

aas_core_codegen/py.typed
We forgot to add ``py.typed`` file to ``aas_core_codegen`` module so
mypy thinks it can not infer the types.
=> Add ``py.typed`` file

aas_core_codegen/rdf_shacl/shacl.py
We mistakenly forgot to remove the unused imports. Due to time pressure,
we skipped remote CI, while the local CI missed these unused imports.
=> Remove unused imports in ``rdf_shacl``

CHANGELOG.rst, aas_core_codegen/__init__.py, setup.py
* Adapt and re-record for aas-core-meta 2022.6.19 (#192)
* Infer non-nullness in the intermediate (#186)
* Fix duplicate inheritance of pattern constraints (#185)
* Exclude external classes stringify assertions (#181)
C#
--
* Make C# classes with children implement interfaces (#190)
* Allow classes without constructor arguments in C# (#189)
* Fix C# generation for CodeInspect and testgen (#187)
* Fix UTF-32 regexes for C# UTF-16-only engine (#183)
* Relax constraints on C# namespace identifiers (#182)
=> Release 0.0.13

aas_core_codegen/csharp/structure/_generate.py, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/types.cs
If a concrete class has one or more concrete descendants, there will be
a corresponding interface generated. Hence this concrete class needs to
implement only that interface, and none more, since the interface will
already specify all the antecedent interfaces.
=> Reduce interfaces if descendants in C#

aas_core_codegen/csharp/description.py, aas_core_codegen/csharp/structure/_generate.py, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/types.cs, test_data/csharp/test_structure/concrete_class_with_descendants/expected_types.cs, test_data/csharp/test_structure/constructor_without_arguments/all_properties_optional/expected_types.cs, test_data/csharp/test_structure/constructor_without_arguments/no_properties/expected_types.cs, tests/csharp/test_description.py
We need to prefix all ``<see cref="..." />`` since conflicts are
possible. For example, if a class has a property ``Entity`` and there is
also an enumerator called ``Entity``.
=> Prefix all ``cref``'s with ``Aas.`` in C#

CHANGELOG.rst, aas_core_codegen/__init__.py, setup.py
This version comprises minor fixes so that we can publish
a pre-release of the C# SDK.
C#
--
* Fix C# for InspectCode (#197)
* Prefix all ``cref``'s with ``Aas.`` in C# (#196)
* Reduce interfaces if descendants in C# (#195)
=> Release 0.0.14

aas_core_codegen/intermediate/__init__.py
We make ``intermediate.TypeAnnotationExceptOptional`` public since
downstream clients (notably, aas-core-testgen3.0rc02) needs it.
=> Make ``TypeAnnotationExceptOptional`` public

aas_core_codegen/csharp/xmlization/_generate.py, aas_core_codegen/intermediate/__init__.py, aas_core_codegen/intermediate/_types.py, aas_core_codegen/xsd/main.py
We often have to check for a primitive type over either primitive type
annotation or a constrained primitive. Therefore, we introduce a
function that encapsulates this logic.
This is also used in downstream clients such as testgen.
=> Encapsulate retrieval of the primitive type

aas_core_codegen/intermediate/_types.py
We have to move the function below in the code so that the mypy can
infer the types correctly. We wanted to merge this in the previous
commit, but mistakenly forgot to include the file.
=> Move `try_primitive_type` in intermediate for mypy

CHANGELOG.rst, aas_core_codegen/__init__.py, setup.py
This version includes minor enhancements to make the work of
the aas-core-testgen a bit easier.
* Encapsulate retrieval of the primitive type (#201)
* Update to aas-core-meta 2022.6.20 (#200)
* Make ``TypeAnnotationExceptOptional`` public (#199)
=> Release 0.0.15

aas_core_codegen/csharp/reporting/_generate.py, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/reporting.cs, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/verification.cs, test_data/csharp/test_main/aas_core_meta.v3rc2/input/snippets/Verification/is_xs_date_time_stamp_utc.cs, test_data/csharp/test_main/aas_core_meta.v3rc2/input/snippets/Verification/value_consistent_with_xsd_type.cs
This is a minor patch that we fix most obvious formatting
inconsistencies. The C# code should still be reformatted with a proper
tool.
=> Reformat C# code

aas_core_codegen/csharp/structure/_generate.py, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/types.cs, test_data/csharp/test_structure/concrete_class_with_descendants/expected_types.cs, test_data/csharp/test_structure/constructor_without_arguments/no_properties/expected_types.cs
We erroneously added a double bracket in the constructor which doesn't
have any arguments.
=> Fix duplicate bracket in C# constructor

aas_core_codegen/csharp/xmlization/_generate.py, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/xmlization.cs
We hard-wire for classes with empty constructors so that InspectCode
does not complain.
=> Wire empty constructors in C# xmlization

aas_core_codegen/csharp/xmlization/_generate.py, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/xmlization.cs
We need to catch ``System.Xml.XmlException``'s when de-serializing
primitive types, since they are thrown when there is suddenly an
unexpected element in the content.
So far we only caught ``System.FormatException`` which is thrown only if
the content does not conform to the expected type.
=> Catch XML exceptions in C# xmlization

test_data/intermediate/real_meta_models/aas_core_meta.v3rc2/expected_symbol_table.txt, test_data/parse/real_meta_models/aas_core_meta.v3rc2/expected_symbol_table.txt
We missed to re-record and erroneously thought that the local CI passed,
which it did not.
This patch re-records the test data.
=> Fix missed re-recordings in 11a98776

aas_core_codegen/csharp/visitation/_generate.py, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/visitation.cs
This is necessary so that we can override them.
=> Make methods virtual in C# ``VisitorThrough``

tests/infer_for_schema/common.py, tests/infer_for_schema/test_len_on_properties.py, tests/infer_for_schema/test_len_on_self.py, tests/infer_for_schema/test_patterns_on_properties.py, tests/infer_for_schema/test_patterns_on_self.py
There are many long statements which we had to break manually to make
them readable.
=> Re-format manually ``tests.infer_for_schema``

README.rst, aas_core_codegen/__init__.py, aas_core_codegen/csharp/verification/_generate.py, aas_core_codegen/infer_for_schema/_stringify.py, aas_core_codegen/intermediate/_translate.py, aas_core_codegen/intermediate/rendering.py, aas_core_codegen/intermediate/type_inference.py, aas_core_codegen/main.py, aas_core_codegen/parse/_translate.py, aas_core_codegen/rdf_shacl/shacl.py, continuous_integration/check_help_in_readme.py, setup.py, tests/csharp/test_main.py, tests/our_jsonschema/test_main.py, tests/rdf_shacl/test_main.py
We make a couple of minor reformats and renamings so that the code lines
fit to lines of 88 characters.
We left out URLs as they are since we would lose the ability to click on
them otherwise.
=> Re-format manually for line width of 88 characters

aas_core_codegen/intermediate/_hierarchy.py, aas_core_codegen/intermediate/_translate.py, aas_core_codegen/intermediate/_types.py, aas_core_codegen/parse/_types.py, tests/csharp/test_description.py, tests/infer_for_schema/common.py, tests/intermediate/test_translate.py, tests/intermediate/test_types.py
We look up our types in the symbol very often. Hence, we implement a
couple of helper methods, ``must_find_*`` to facilitate the typing
around the lookups.
=> Introduce more of ``must_find_*`` methods

tests/intermediate/test_translate.py
This is a minor fix that allows us to test against models outside of the
repository. For example, when we install aas-core-meta as editable
package in our virtual environment.
=> Fix tests of intermediate for external model paths

.idea/aas-core-csharp-codegen.iml, .idea/misc.xml, aas_core_codegen/parse/_rules.py
The remote CI failed in the previous patch for Python 3.9 and 3.10 due
to breaking changes in the ``ast`` module. This patch fixes the issue by
branching on the Python version.
=> Fix parsing for Python 3.9 and 3.10

aas_core_codegen/csharp/transpilation.py, aas_core_codegen/csharp/verification/_generate.py, aas_core_codegen/intermediate/__init__.py, aas_core_codegen/intermediate/_stringify.py, aas_core_codegen/intermediate/_translate.py, aas_core_codegen/intermediate/_types.py, aas_core_codegen/intermediate/type_inference.py, aas_core_codegen/parse/tree.py, aas_core_codegen/smoke/main.py, setup.py, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/verification.cs, test_data/intermediate/real_meta_models/aas_core_meta.v3rc2/expected_symbol_table.txt, test_data/intermediate/unexpected/invariant/class_invariant_uses_re/expected_error.txt, test_data/intermediate/unexpected/invariant/class_invariant_uses_re/meta_model.py, test_data/intermediate/unexpected/invariant/invariant_of_constrained_primitive_uses_re/expected_error.txt, test_data/intermediate/unexpected/invariant/invariant_of_constrained_primitive_uses_re/meta_model.py, test_data/parse/real_meta_models/aas_core_meta.v3rc2/expected_symbol_table.txt, test_data/smoke/test_main/unexpected/pattern_verification_unparsable_regex/direct_match/expected_stderr.txt
We refactor the transpilation so that it works on general verification
functions, not only on pattern matching.
This is important in particular for code re-use in constraints, such as
``is_model_reference_to``.
=> Transpile general verification functions

aas_core_codegen/csharp/description.py, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/types.cs, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/verification.cs, tests/csharp/test_description.py
The paragraph breaks are hard to get correct, and we actually got them
completely wrong in the first iteration. This patch implements a much
more complex rendering of docutils nodes to C# HTML-like documentation
comments.
=> Fix paragraph breaks in C# code generation

aas_core_codegen/csharp/jsonization/_generate.py, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/jsonization.cs
We remove an unnecessary and utterly confusing trailing whitespace in an
error message in the generated C# code for JSON de/serialization.
=> Fix error message in c# jsonization

aas_core_codegen/csharp/jsonization/_generate.py, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/jsonization.cs
So far, we ignored additional properties in JSON. This can lead to
unexpected data loss, and is also not consistent with XML, which accepts
no additional properties.
In this change, we reject all JSON data with unexpected additional
properties.
=> Make C# JSON de/serialization strict

aas_core_codegen/main.py, aas_core_codegen/parse/_translate.py, aas_core_codegen/smoke/main.py, continuous_integration/mypy.ini, continuous_integration/precommit.py, requirements.txt, tests/parse/test_retree.py
The dependency asttokens introduced type annotations in the version
2.0.8. This revealed a couple of typing errors in our code, which this
patch fixes.
=> Fix mypy errors due to asttokens 2.0.8

aas_core_codegen/rdf_shacl/shacl.py, setup.py, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/verification.cs, test_data/intermediate/real_meta_models/aas_core_meta.v3rc2/expected_symbol_table.txt, test_data/jsonschema/test_main/aas_core_meta.v3rc2/examples/expected/empty/empty_environment_with_optional_properties_empty.json, test_data/jsonschema/test_main/aas_core_meta.v3rc2/expected_output/schema.json, test_data/parse/real_meta_models/aas_core_meta.v3rc2/expected_symbol_table.txt, test_data/xsd/test_main/aas_core_meta.v3rc2/examples/expected/empty/empty_environment_with_optional_properties_empty.xml, test_data/xsd/test_main/aas_core_meta.v3rc2/expected_output/schema.xsd
We update for [aas-core-meta 08f5bb1], which requires that
all lists are either null or at least have a length 1 (except for a few
exceptions).
We therefore have to consider a special case in SHACL schema generation
since SHACL does not distinguish between empty and null properties.
Finally, we update the test data to reflect [aas-core-meta 08f5bb1].
[aas-core-meta 08f5bb1]: https://github.com/aas-core-works/aas-core-meta/commit/08f5bb1
=> Update logic for min. length of 1 for lists

aas_core_codegen/infer_for_schema/__init__.py, aas_core_codegen/infer_for_schema/_len.py, aas_core_codegen/infer_for_schema/_pattern.py, aas_core_codegen/infer_for_schema/_set.py, aas_core_codegen/infer_for_schema/match.py
Downstream clients, such as aas-core-meta, need to also match
invariants. Therefore, we expose ``infer_for_schema._common`` as a
public module ``infer_for_schema.match`` so that this logic can be used
by clients as well.
=> Expose ``infer_for_schema._common`` as ``match``

aas_core_codegen/parse/_translate.py
We add the word ``object`` to a list of reserved keywords in the parse
stage since a conflict already happened with the security part of the
meta-model.
=> Consider ``object`` a reserved keyword

aas_core_codegen/xsd/main.py, test_data/xsd/test_main/aas_core_meta.v3rc2/expected_output/schema.xsd
We specify ``maxOccurs`` of 1 for elements representing optional
properties. Even though the default value for ``maxOccurs`` is 1, this
change in XSD helps to avoid confusion for the less XSD-savvy readers.
Fixes #240.
=> Specify ``maxOccurs`` for optional elements in XSD

test_data/rdf_shacl/test_main/aas_core_meta.v3rc2/input/snippets/.gitignore
Currently, RDF+SHACL generation does not depend on any snippets, which
will probably change in the near future. Therefore, we keep the logic
for reading the snippets from a directory, and create an empty snippets
directory in the test data.
We mistakenly broke the tests since Git automatically removed empty
directories.
=> Create test empty snippets for RDF+SHACL

aas_core_codegen/specific_implementations.py
We ignore files starting with a dot (".") when listing the snippets.
This is important, so that special files such as ``.gitignore`` are not
included in the snippets.
=> Ignore hidden files in snippets

aas_core_codegen/jsonschema/main.py, test_data/jsonschema/test_main/aas_core_meta.v3rc2/expected_output/schema.json
We sort all the enumeration literals in JSON schema so that it is easier
to diff two versions of the schema.
=> Sort all enumeration literals in JSON schema

aas_core_codegen/rdf_shacl/common.py, aas_core_codegen/rdf_shacl/rdf.py, aas_core_codegen/rdf_shacl/shacl.py, test_data/rdf_shacl/test_main/aas_core_meta.v3rc2/expected_output/rdf-ontology.ttl, test_data/rdf_shacl/test_main/aas_core_meta.v3rc2/expected_output/shacl-schema.ttl
We used ``xsd:`` in RDF+SHACL and ``xs:`` in XSD. This change makes it
uniform, and we use ``xs:`` everywhere.
=> Make ``xs:`` prefix consistent in XSD/RDF/SHACL

setup.py, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/types.cs, test_data/csharp/test_main/aas_core_meta.v3rc2/input/snippets/Types/Data_element/category_or_default.cs, test_data/intermediate/real_meta_models/aas_core_meta.v3rc2/expected_symbol_table.txt
We update the development requirements to and re-record the test data
for [aas-core-meta 1df1729].
So far, we referenced the properties as properties of a concrete class
in the documentation instead of referencing them to the most abstract
class which defines them.
This creates problems with [docfx] in C# so we reference the
properties as properties of the abstract class.
We also update the implementation-specific snippets for C# which also
referenced the properties in the concrete class instead of the abstract
one.
[aas-core-meta 1df1729]: https://github.com/aas-core-works/aas-core-meta/commit/1df1729
[docfx]: https://dotnet.github.io/docfx/
=> Update test data to aas-core-meta 1df1729

aas_core_codegen/rdf_shacl/common.py, aas_core_codegen/rdf_shacl/rdf.py, aas_core_codegen/rdf_shacl/shacl.py, test_data/rdf_shacl/test_main/aas_core_meta.v3rc2/expected_output/rdf-ontology.ttl, test_data/rdf_shacl/test_main/aas_core_meta.v3rc2/expected_output/shacl-schema.ttl
We hard-wire the handling of the class ``Lang_string`` in RDF+SHACL, and
represent it as the native ``rdf:langString``.
Admittedly, this is hacky. We could have made the class ``Lang_string``
implementation-specific and defined its ``rdfs:range`` manually as
a snippet.
However, we decided against that as such a design would force us to
define ``langString`` for every language and schema which do not
natively support it, write custom data generation methods *etc.* Given
that RDF+SHACL codegen is one out of many code generators we leave the
other code generators and test data generators as simple as possible,
and make the RDF+SHACL code generator a bit hacky in return.
=> Hard-wire ``Lang_string`` in RDF+SHACL

aas_core_codegen/rdf_shacl/common.py, test_data/rdf_shacl/test_main/aas_core_meta.v3rc2/expected_output/rdf-ontology.ttl, test_data/rdf_shacl/test_main/aas_core_meta.v3rc2/expected_output/shacl-schema.ttl
So far, we represented byte arrays as ``xs:byte`` in RDF+SHACL. This is
wrong as RDF follows XML. Hence, we fix the range of byte arrays to
``xs:base64Binary``, just as in XSD.
=> Represent bytes as ``base64Binary`` in RDF+SHACL

aas_core_codegen/rdf_shacl/common.py, aas_core_codegen/rdf_shacl/main.py, aas_core_codegen/rdf_shacl/rdf.py, aas_core_codegen/rdf_shacl/shacl.py, aas_core_codegen/xsd/main.py, test_data/rdf_shacl/test_main/aas_core_meta.v3rc2/expected_output/rdf-ontology.ttl, test_data/rdf_shacl/test_main/aas_core_meta.v3rc2/expected_output/shacl-schema.ttl, test_data/xsd/test_main/aas_core_meta.v3rc2/expected_output/schema.xsd
In XSD, RDF and SHACL, ``Value_data_type`` should be represented as
``xs:anySimpleType`` instead of a string. We hard-wire how we represent it
in XSD and RDF+SHACL schema generators.
Similar to ``Lang_string``, this hard-wiring is hacky. We could have made
the class ``Value_data_type`` implementation-specific and defined it
manually as a snippet.
However, we decided against that. This would be a major hurdle for
other code and test data generators (which can treat ``Value_data_type``
simply as string). Therefore, we make the XML and RDF+SHACL schema
generators a bit more hacky instead of complicating the other
generators.
If in the future, for whatever reason, the semantic of ``Value_data_type``
changes (or the type is renamed), be careful to maintain backwards
compatibility! You probably …
=> Hard-wirte `Value_data_type` to `xs:anySimpleType`

aas_core_codegen/intermediate/_stringify.py, aas_core_codegen/intermediate/_types.py, test_data/intermediate/expected/constant/constant_set/of_enum/expected_symbol_table.txt, test_data/intermediate/expected/enumeration/expected_symbol_table.txt, test_data/intermediate/real_meta_models/aas_core_meta.v3rc2/expected_symbol_table.txt
We map the enumeration literals by their values to allow for quick
lookups. While we do not use this functionality in aas-core-codegen, it
is very useful for the downstream code such as aas-core3.0rc02-testgen.
=> Map literals by value in intermediate layer

aas_core_codegen/rdf_shacl/common.py, aas_core_codegen/rdf_shacl/rdf.py, aas_core_codegen/rdf_shacl/shacl.py, test_data/rdf_shacl/test_main/aas_core_meta.v3rc2/expected_output/rdf-ontology.ttl, test_data/rdf_shacl/test_main/aas_core_meta.v3rc2/expected_output/shacl-schema.ttl
We undo the pull request #265 since RDF and SHACL can not deal with
`xs:anySimpleType`.
Please see this comment on [issue 210 of admin-shell-io/aas-specs].
[issue 210 of admin-shell-io/aas-specs]: https://github.com/admin-shell-io/aas-specs/issues/210#issuecomment-1234331148
=> Undo `anySimpleType` in RDF

aas_core_codegen/xsd/main.py, test_data/xsd/test_main/aas_core_meta.v3rc2/expected_output/schema.xsd, tests/xsd/test_main.py
We hard-code the member types which are allowed as `Value_data_type`.
This is really hacky -- as we iterate over concrete enumeration from the
model. If the model changes, and provides no ``Data_type_def_XSD`` or
``Value_data_type`` changes the semantics *etc.*, the generator for XML
schema is messed up.
Yet, we deliberately decided to keep other generators simple, and make
XML generator hacky for this particular pain point.
If in the future, for whatever reason, the semantic of
``Value_data_type`` changes (or the type is renamed), be careful to
maintain backwards compatibility here! You probably want to
distinguish different versions of the meta-model and act accordingly.
At that point, it might also make sense to refactor this schema
generator to a separate repository, and fix it to a …
=> Restrict value data types in XML

aas_core_codegen/xsd/main.py, test_data/xsd/test_main/aas_core_meta.v3rc2/expected_output/schema.xsd, tests/xsd/test_main.py
We hard-wire the constrained primitive `Value_data_type` to a simple type with `xs:string` restriction in the XSD generator.
Previously, we hard-wired it to a list corresponding to `Data_type_def_XSD`. This list, however, is only compatible with XSD 1.1 and breaks XSD 1.0. Since the effect of the restriction is identical, we opt for compatibility with XSD 1.0.
See also the important note in the commit [5ae9681] regarding how hacky this whole hard-wiring is. In the near future, you should re-consider to refactor the XSD generator out of this repository and pin it to a range of AAS meta-model versions.
[5ae9681]: https://github.com/aas-core-works/aas-core-codegen/commit/5ae9681632477852bda9b7ced18730a22b6492bd
=> Restrict `Value_data_type` to `xs:string` in XSD

aas_core_codegen/csharp/structure/_generate.py, aas_core_codegen/csharp/visitation/_generate.py, aas_core_codegen/infer_for_schema/_stringify.py, aas_core_codegen/intermediate/_stringify.py, aas_core_codegen/intermediate/_translate.py, aas_core_codegen/intermediate/construction.py, aas_core_codegen/parse/retree/_parse.py, aas_core_codegen/smoke/main.py, tests/csharp/test_structure.py, tests/csharp/test_verification.py, tests/intermediate/test_translate.py, tests/parse/test_retree.py
Black reformatted back a lot of line breaks in interpolated strings. This makes the string literals barely readable, so we join the adjacent string literals for better readability.
=> Fix undone line-breaks in interpolated strings

aas_core_codegen/csharp/structure/_generate.py, aas_core_codegen/intermediate/_stringify.py, aas_core_codegen/intermediate/_translate.py, aas_core_codegen/intermediate/_types.py, aas_core_codegen/intermediate/construction.py, test_data/intermediate/expected/class/empty/expected_symbol_table.txt, test_data/intermediate/expected/class/implementation_specific_method/expected_symbol_table.txt, test_data/intermediate/expected/class/inheritance/expected_symbol_table.txt, test_data/intermediate/expected/class/methods_with_contracts/expected_symbol_table.txt, test_data/intermediate/expected/class/only_method_no_property/expected_symbol_table.txt, test_data/intermediate/expected/class/only_property_no_method/expected_symbol_table.txt, test_data/intermediate/expected/interface/basic/expected_symbol_table.txt, test_data/intermediate/expected/interface/empty/expected_symbol_table.txt, test_data/intermediate/expected/interface/inheritance/expected_symbol_table.txt, test_data/intermediate/expected/interface/method_signature/expected_symbol_table.txt, test_data/intermediate/expected/interface/only_constructor/expected_symbol_table.txt, test_data/intermediate/expected/type_annotation/atomic/expected_symbol_table.txt, test_data/intermediate/expected/type_annotation/subscripted/expected_symbol_table.txt, test_data/intermediate/real_meta_models/aas_core_meta.v3rc2/expected_symbol_table.txt, tests/intermediate/test_translate.py
Since we now generate the code also in languages which allow multiple-inheritance (Python), we have to capture the original constructor statements, besides the in-line statements we captured for the languages without multiple-inheritance (at this moment, C#).
=> Capture original and in-lined construction

tests/test_common.py
We restore the tests previously living in
`tests.csharp.test_verification` to `tests.test_common`. This was a mistake in the previous commit (#a2ec3fdc).
=> Restore tests for re-flowing of text

test_data/csharp/test_main/aas_core_meta.v3rc2/input/snippets/Verification/data_specification_IEC_61360s_have_definition_at_least_in_english.cs, test_data/csharp/test_main/aas_core_meta.v3rc2/input/snippets/Verification/is_xs_date_time_stamp_utc.cs, test_data/csharp/test_main/aas_core_meta.v3rc2/input/snippets/Verification/submodel_element_is_of_type.cs
We discovered a couple of (minor) bugs in the code while we were working on the generator for Python SDK. This patch includes the fixes, and also harmonizes the names with the (future) Python SDK for clarity.
=> Fix C# snippets after working on Python SDK

aas_core_codegen/intermediate/_translate.py, test_data/intermediate/real_meta_models/aas_core_meta.v3rc2/expected_symbol_table.txt, tests/csharp/test_description.py, tests/intermediate/test_translate.py
Previously, due to ignorance, we annotated references with different prefixes (attributes with ``~`` and classes and constants with ``.``). Eventually, we learned more about Sphinx and how it deals with references (see [1]).
In this change, we sort out the referencing and make it a bit clearer:
* attributes, classes and constants must be references as-are,
* appearance prefixes ``!`` and ``~`` are ignored (as target languages usually do not work like Sphinx), and
* relaxed qualified names (references prefixed with a ``.``) are disallowed as we can only resolve references *within* the meta-model and not outside it.
The unit tests are expected to fail as we have to update aas-core-meta after this change to avoid aas-core-meta's unit tests to fail.
[1]: …
=> Sort out handling of reference paths

aas_core_codegen/csharp/xmlization/_generate.py, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/xmlization.cs
We did not produce the correct XPaths in xmlization exceptions, but this went unnoticed as the current XPaths resembled the correct ones.
This patch prepends the necessary element names, so that now the exceptions can be correctly traced in the problematic XML documents.
Addresses
https://github.com/aas-core-works/aas-core3.0rc02-csharp/issues/68.
=> Fix XPaths in C# xmlization exceptions

README.rst, aas_core_codegen/rdf_shacl/main.py, continuous_integration/precommit.py, setup.py
We only considered excludes in the ``--overwrite`` mode of the pre-commit checks, but forgot to include them also in the non-invasive checks as well. This patch fixes the issue, and the CI runs again.
=> Make remote CI work again

aas_core_codegen/python/xmlization/_generate.py, test_data/python/test_main/aas_core_meta.v3rc2/expected_output/xmlization.py
We mistakenly escape an ampersand to ``&amp`` instead of ``&amp;`` (mind the semi-colon), which causes XML errors in de-serialization.
The mistake went unnoticed due to a bug in the unit test code where the examples were not globbed recursively, but only at the top-level example directory.
=> Fix escaping in XML serialization in Python

test_data/python/test_main/aas_core_meta.v3rc2/expected_output/verification.py, test_data/python/test_main/aas_core_meta.v3rc2/input/snippets/Verification/is_xs_date_time_stamp_utc.py, test_data/python/test_main/aas_core_meta.v3rc2/input/snippets/Verification/value_consistent_with_xsd_type.py
Due to a glitch in the unit test code of the Python SDK, we did not test the handling of XML values properly. The examples were not globbed recursively, but only at the top-level example directory.
In this patch, we make a couple of minor changes which now fixes the test cases so that the unit tests pass:
* All matching functions (``matches_*``) return a boolean, but we checked for ``None``, which basically invalidated the checks.
* We use a short regular expression to parse dates. The previous code based on ``.split('-')`` was too error prone.
* We did not properly check for infinity in ``xs:float``'s. After this change, we check for inifinity just like for ``xs::double``.
=> Fix validation of XML types in Python

test_data/python/test_main/aas_core_meta.v3rc2/expected_output/types.py, test_data/python/test_main/aas_core_meta.v3rc2/expected_output/verification.py, test_data/python/test_main/aas_core_meta.v3rc2/input/snippets/Types/Extension/value_type_or_default.py, test_data/python/test_main/aas_core_meta.v3rc2/input/snippets/Verification/properties_or_ranges_have_value_type.py, test_data/python/test_main/aas_core_meta.v3rc2/input/snippets/Verification/submodel_element_is_of_type.py, test_data/python/test_main/aas_core_meta.v3rc2/input/snippets/Verification/value_consistent_with_xsd_type.py
We changed the naming in b13f75b, but forgot to update the Python snippets accordingly.
In this patch, we change the snippets and test them against the unit tests generated in aas-core3.0rc02-python.
=> Fix test data snippets for Python V3RC02

test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/verification.cs, test_data/csharp/test_main/aas_core_meta.v3rc2/input/snippets/Verification/is_xs_date_time_stamp_UTC.cs, test_data/csharp/test_main/aas_core_meta.v3rc2/input/snippets/Verification/value_consistent_with_xsd_type.cs
We explicitly tested for zero and BCE years in
[aas-core3.0rc02-testgen eeba8f71] which revealed that the C# SDK did not handle those edge cases correctly.
In this patch, we re-write the snippets for date verification in the test data for C# SDK.
[aas-core3.0rc02-testgen eeba8f71]: https://github.com/aas-core-works/aas-core3.0rc02-testgen/commit/eeba8f71
=> Fix date verification of BCE and zero years in C#

test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/verification.cs, test_data/csharp/test_main/aas_core_meta.v3rc2/input/snippets/Verification/is_xs_date_time_stamp_UTC.cs
We were too hasty to merge in the changes in 1d12eaed which cause a couple of minor code inspection issues.
In this patch, we fix the snippets in the test data so that the code inspection for C# SDK passes.
=> Fix C# code inspection issues due to 1d12eaed

aas_core_codegen/csharp/xmlization/_generate.py, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/xmlization.cs
The docs for XML serialization for C# has been outdated. It still listed the namespace and the prefix argument from the original design which has been removed in the meanwhile.
This patch fixes the generator so that the generated docs are in sync with the generated code.
=> Fix xmlization docs for C# in test data

aas_core_codegen/rdf_shacl/common.py, aas_core_codegen/rdf_shacl/rdf.py, aas_core_codegen/rdf_shacl/shacl.py, aas_core_codegen/xsd/main.py
We hard-wire ``Lang_string`` and ``Value_data_type`` in RDF and XSD generators, respectively. This is indeed hacky (see the explanations in the patch), but this way we keep the other code and test data generators much simpler.
Previously, if the expected types ``Lang_string`` and ``Value_data_type`` have not been defined in the meta-model, we raised exceptions which confused the user. In this patch, we report informative errors explaining the background to the user as well.
=> Report errors if classes missing for RDF and XSD

aas_core_codegen/csharp/naming.py, aas_core_codegen/naming.py
We refactor the code in the ``naming`` module into fewer functions, so that the dependent naming modules can re-use them. This makes it more obvious for the reader which casing is used.
While duplication is in similar cases often better for readability, we already observed related bugs in the TypeScript generator (which is still a work-in-progress), so we react accordingly.
=> De-duplicate code in ``naming``

aas_core_codegen/csharp/main.py, aas_core_codegen/python/main.py
In the ``main`` of the C# and Python generator we mistakenly ignored the verification errors due to misnaming of the local variable. We fix the issue in this patch.
=> Fix ignored verification erros in ``main``

aas_core_codegen/csharp/structure/_generate.py
While we do not test for this logic at the moment, we reviewed the C# code while writing the TypeScript generator (which is still work-in-progress). It turns out that we missed the case where there are statements in C# constructors, but no arguments.
In this patch, we generate the constructors as soon as they have statements, regardless of the number of arguments.
=> Generate empty constructors in C#

aas_core_codegen/python/jsonization/_generate.py, test_data/python/test_main/aas_core_meta.v3rc2/expected_output/jsonization.py
We fix the error where we mistakenly wrote "Containers" instead of a single "container" in ``IndexSegment``. The ``IndexSegment`` refers to an array so there can not be multiple containers.
=> Fix minor typo in Python jsonization

aas_core_codegen/python/common.py, aas_core_codegen/python/transpilation.py, aas_core_codegen/python/verification/_generate.py
We introduced a couple of innoucous invalid references in Python generator by copy/pasting from C# generator when we first wrote it.
We rectify these invalid references to Python in this patch.
=> Fix erroneous references to C# from Python

aas_core_codegen/csharp/structure/_generate.py, aas_core_codegen/csharp/unrolling.py, aas_core_codegen/python/structure/_generate.py, aas_core_codegen/python/unrolling.py
Since ``Unroller`` is an abstract class, and intentionally so, we rename it to ``AbstractUnroller`` to aid the reader so that it is obvious that the concrete class is an implementation, while the abstract class gives only a scaffolding.
=> Rename ``Unroller`` to ``AbstractUnroller``

aas_core_codegen/python/structure/_generate.py
While we do not test for this logic at the moment, we reviewed the Python code while writing the TypeScript generator (which is still work-in-progress). It turns out that we missed the case where there are statements in constructors, but no arguments.
In this patch, we generate the constructors as soon as they have statements, regardless of the number of arguments (which can be zero or more).
=> Generate constructors with no arguments in Python

aas_core_codegen/python/transpilation.py
We reviewed the code while developping TypeScript generator (which is still a work-in-progress). The review revealed that we missed to indent the arguments to a method call in transpilation to Python.
=> Indent args in transpiled method calls in Python

aas_core_codegen/python/transpilation.py
We simply transpiled the function name to Python casing in transpilation. While this works for the meta-models designed so far, it is a ticking bomb to explode if we have cross-module function calls.
This patch fixes the issue by delegating the transpilation of the name to the concrete implementation in the abstract transpiler class.
=> Fix transpilation of function names in Python

test_data/python/test_main/aas_core_meta.v3rc2/expected_output/verification.py, test_data/python/test_main/aas_core_meta.v3rc2/input/snippets/Verification/value_consistent_with_xsd_type.py
We make the verification functions ``is_xs_date*`` to match against the patterns first to avoid bugs related to unexpected date/time formats.
=> Fix ``is_xs_date*`` in Python to match first

test_data/python/test_main/aas_core_meta.v3rc2/expected_output/verification.py, test_data/python/test_main/aas_core_meta.v3rc2/input/snippets/Verification/is_xs_date_time_stamp_UTC.py, test_data/python/test_main/aas_core_meta.v3rc2/input/snippets/Verification/value_consistent_with_xsd_type.py
We compared against ``is False`` instead of using ``not`` operator. This is much less readable, and in cases where ``matches_*`` functions return non-boolean, can lead to bugs.
This patch fixes the issue by consistently using ``not`` operator.
=> Fix Python verification to check for falsy matches

.idea/runConfigurations/Python_tests_in_tests.xml, .idea/runConfigurations/precommit_w__parallel_tests.xml, continuous_integration/precommit.py
We had problems with the pre-commit scripts since commands could not be found in the environment. This patch fixes the issue by invoking pre-commit commands such as black or mypy as modules through ``sys.executable``.
=> Make pre-commit use ``sys.executable``

aas_core_codegen/main.py
We left a stale error message in the main program referring to JSON snippets instead of general snippets.
=> Fix error message on reading snippets

aas_core_codegen/intermediate/__init__.py
We want to allow the downstream generators to discrimanate exhaustively on the verification functions, and therefore make ``VerificationUnion`` public in the ``intermediate`` module.
=> Make ``VerificationUnion`` public

aas_core_codegen/main.py, aas_core_codegen/run.py
We refactor the loading of meta-model to `run` module so that downstream consumers can access the meta-models more easily. This is such a common workflow in clients that it is worth the encapsulation.
=> Refactor loading function to `run`

.idea/runConfigurations/precommit_w__parallel_tests.xml, aas_core_codegen/typescript/structure/_generate.py, test_data/typescript/test_main/aas_core_meta.v3rc2/expected_output/types.ts
We generate a function to check whether two instances match in type at runtime in TypeScript. For example, this is used in the React editor where we assert that snapshot and modifiable instances are of the same type.
=> Add runtime type matching to TypeScript

aas_core_codegen/common.py, aas_core_codegen/typescript/common.py
We let the `Identifier` inherit from `Stripped` so that we can relax the type module prefix used in the generation of TypeScript type definitions.
=> Relax type module in typescript generation

aas_core_codegen/typescript/verification/_generate.py, test_data/typescript/test_main/aas_core_meta.v3rc2/expected_output/verification.ts
We grouped properties of constrained primitives with all the other properties in the recusrion block in TypeScript. This is obviously wrong, as we want to verify the constrained primitives regardless of the recursion in the verification context.
=> Verify constr. primitives in non-recursion in TS

aas_core_codegen/infer_for_schema/_inline.py, aas_core_codegen/jsonschema/main.py, test_data/jsonschema/test_main/test_regression_missing_constraints/expected_output/schema.json, test_data/jsonschema/test_main/test_regression_missing_constraints/expected_output/stdout.txt, test_data/jsonschema/test_main/test_regression_missing_constraints/input/snippets/schema_base.json, test_data/jsonschema/test_main/test_regression_missing_constraints/meta_model.py, tests/infer_for_schema/test_len_on_properties.py, tests/our_jsonschema/test_main.py
We skipped to define constraints on properties which are inherited. This is a bug, as the schema can verify them with ``allOf`` just fine.
=> Fix missing constraints on inherited props in JSON

.idea/aas-core-csharp-codegen.iml, test_data/jsonschema/test_main/test_regression_missing_constraints/meta_model.py, tests/common.py, tests/our_jsonschema/test_main.py
So far, we only iterated over the `test_main` directory of JSON Schema generator to collect the test cases. In the immediate future, we will generalize this logic to RDF+SHACL tests as well.
Hence, we refactor the functionality of the search for test cases into `tests.common`.
=> Refactor test case finding to `tests.common`

aas_core_codegen/rdf_shacl/common.py, aas_core_codegen/rdf_shacl/rdf.py, aas_core_codegen/rdf_shacl/shacl.py, test_data/rdf_shacl/test_main/regression_when_lang_string_class_is_missing/expected_output/rdf-ontology.ttl, test_data/rdf_shacl/test_main/regression_when_lang_string_class_is_missing/expected_output/shacl-schema.ttl, test_data/rdf_shacl/test_main/regression_when_lang_string_class_is_missing/expected_output/stdout.txt, test_data/rdf_shacl/test_main/regression_when_lang_string_class_is_missing/input/snippets/.gitignore, test_data/rdf_shacl/test_main/regression_when_lang_string_class_is_missing/meta_model.py, tests/rdf_shacl/test_main.py
We assumed that ``Lang_string`` will always be defined, and hard-wired certain parts of the RDF+SHACL codegen to that particular class.
However, this assumption did not hold long: already the first iteration of V3.0 of the metamodel came without a ``Lang_string``.
In this patch, we make RDF+SHACL more robust in face of missing ``Lang_string``, and allow the generation without its definition.
=> Fix RDF+SHACL when ``Lang_string`` is missing

aas_core_codegen/specific_implementations.py
So far, we only tested happy paths when reading the snippets. It turned out that the logic is not so robust when reading an arbitrary directory, which we found out unintentionally.
This patch fixes the issue, but we lack the time to implement a proper unit test, unfortunately.
=> Make reading of snippets more robust

aas_core_codegen/csharp/common.py, aas_core_codegen/csharp/copying/_generate.py, aas_core_codegen/csharp/jsonization/_generate.py, aas_core_codegen/csharp/structure/_generate.py, aas_core_codegen/csharp/verification/_generate.py, aas_core_codegen/csharp/visitation/_generate.py, aas_core_codegen/csharp/xmlization/_generate.py, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/copying.cs, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/jsonization.cs, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/types.cs, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/verification.cs, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/visitation.cs, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/xmlization.cs, test_data/csharp/test_structure/concrete_class_with_descendants/expected_types.cs, test_data/csharp/test_structure/constructor_without_arguments/all_properties_optional/expected_types.cs, test_data/csharp/test_structure/constructor_without_arguments/no_properties/expected_types.cs, test_data/csharp/test_verification/builtin_functions/len/on_list/expected_verification.cs, test_data/csharp/test_verification/builtin_functions/len/on_str/expected_verification.cs
We operate on *interfaces* instead of concrete classes to allow for custom extensions and wrappers around our model classes.
Originally, we used type overloading to dispatch the visit calls. After we decided to support custom wrappers and enhancements to our classes, we had to switch here to interfaces instead of concrete classes. The type overloading does not work anymore in this setting, as descendants of *concrete* classes would be wrongly dispatched. That is why we dispatch explicitly, by having different visit method names instead of mere type overloads.
=> Make C# code operate on interfaces

test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/visitation.cs
We forgot to re-record the test data once we fixed the trailing spaces in the generating code.
=> Reformat trailing space in recorded C# tests

aas_core_codegen/smoke/main.py, test_data/smoke/test_main/unexpected/type_error/expected_stderr.txt, test_data/smoke/test_main/unexpected/type_error/meta_model.py
We encountered various errors during the design of the aas-core-meta V3 which would have been prevented if only we transpiled to C# (or any other language). Notably, we needed type inference which was missing in the current smoke tests.
This patch mocks all the implementation specific snippets and transpiles to C# in the smoke command, so that the errors in the meta-models can be discovered earlier during the design.
=> Transpile everything to C# in smoke mode

aas_core_codegen/intermediate/type_inference.py
We improve error messages when a type has been inferred as `Optional`, but a non-optional type has been expected.
=> Improve errors on unexpected type inference

test_data/rdf_shacl/test_main/unexpected/regression_len_constraint_on_class_property/expected_output/stderr.txt, tests/rdf_shacl/test_main.py
Due to lack of time (deadlines + nearing holidays), we ignored the minor issue failing the remote CI. Namely, the paths in the recorded errors for RDF+SHACL were stored with the absolute paths, and thus failed on the remote machine.
=> Fix tests failing in remote CI

aas_core_codegen/naming.py, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/jsonization.cs, test_data/jsonschema/test_main/aas_core_meta.v3rc2/expected_output/schema.json, test_data/python/test_main/aas_core_meta.v3rc2/expected_output/jsonization.py, test_data/typescript/test_main/aas_core_meta.v3rc2/expected_output/jsonization.ts
The current naming algorithm for model types turned out to be rather fragile. Namely, we used CamelCase except for abbreviations, which were left as-are. This was brittle: if we forgot to uppercase the abbreviation in the meta-model, and published the JSON schema, there was no way to put the Gini back into the bottle.
Instead, in V3, we introduce a simpler, but also a more robust algorithm: we simply CamelCase everything, including the abbreviations.
=> Change JSON naming of model types for V3

aas_core_codegen/jsonschema/main.py, test_data/jsonschema/test_main/aas_core_meta.v3rc2/expected_output/schema.json
Following the decision in the IDTA workstream AAS, we introduce `*_choice` definitions in JSON schema. This makes the schema much stricter.
For example, `value` property must conform in type to the corrsponding model type.
The issue was originally raised in:
https://github.com/admin-shell-io/aas-specs/issues/251
=> Introduce `*_choice` in JSON schema

setup.py, test_data/intermediate/real_meta_models/aas_core_meta.v3rc2/expected_symbol_table.txt, test_data/python/test_main/aas_core_meta.v3rc2/expected_output/types.py, test_data/typescript/test_main/aas_core_meta.v3rc2/expected_output/types.ts
We update the test data for V3RC02 to [aas-core-meta cbbc2d2] to keep them up-to-date.
[aas-core-meta cbbc2d2]: https://github.com/aas-core-works/aas-core-meta/commit/cbbc2d2
=> Update test data to aas-core-meta cbbc2d2

aas_core_codegen/rdf_shacl/rdf.py, test_data/rdf_shacl/test_main/unexpected/regression_len_constraint_on_class_property/expected_output/stderr.txt, tests/rdf_shacl/test_main.py
We fix a minor issue (unused import) that our local pylint missed, but
the pylint running on the remote continuous integration server detected.
We have no clue why our local pylint and the remote one differ on this
point.
Additionally, we fix recorded test data where we had discrepancy due to
Linux *versus* Windows paths. The fixed test data uses normalized paths
independent of the underlying OS.
=> Fix CI errors not reported locally

aas_core_codegen/python/verification/_generate.py
When there is no verification for a class, we just ``passed`` instead of returning an empty iterator.
See [this StackOverflow question] for more information.
[this StackOverflow question]: https://stackoverflow.com/questions/13243766/how-to-define-an-empty-generator-function
=> Fix empty verification in Python

test_data/python/test_main/aas_core_meta.v3/expected_output/verification.py
We have to re-generate the Python test data after #345.
=> [V3] Re-generate test data after #345

aas_core_codegen/typescript/verification/_generate.py, test_data/typescript/test_main/aas_core_meta.v3/expected_output/verification.ts, test_data/typescript/test_main/aas_core_meta.v3/input/snippets/package_identifier.txt
We erroneously hard-wired references to package identifier of V3RC02 in TypeScript codegen.
This patch introduces a snippet to let the user specify the package identifier so that the module comment description corresponds to the actual version of the SDK.
=> Remove referenes to V3RC02 from TypeScript codegen

test_data/typescript/test_main/aas_core_meta.v3/expected_output/types.ts, test_data/typescript/test_main/aas_core_meta.v3/expected_output/verification.ts, test_data/typescript/test_main/aas_core_meta.v3/input/snippets/Types/Has_kind/kind_or_default.ts, test_data/typescript/test_main/aas_core_meta.v3/input/snippets/Verification/ID_shorts_of_variables_are_unique.ts, test_data/typescript/test_main/aas_core_meta.v3/input/snippets/Verification/lang_strings_have_unique_languages.ts
We fix issues with TypeScript snippets while testing them in aas-core3.0-typescript.
There was a bug related to detection of non-JSON objects in jsonization, which we will fix in the next commit.
=> [V3] Fix snippets for TypeScript

aas_core_codegen/typescript/jsonization/_generate.py, test_data/typescript/test_main/aas_core_meta.v3rc2/expected_output/jsonization.ts, test_data/typescript/test_main/aas_core_meta.v3rc2/expected_output/verification.ts
In JavaScript, arrays are objects. This makes our checks during the deserialization to fail for missing properties, but not for the incorrect type.
This patch introduces a proper check that the value is not an array.
=> Fix TypeScript mistaking JSON arrays for objects

aas_core_codegen/typescript/verification/_generate.py
When the class has no invariants defined, the eslint complains that the instance variable `that` is not used.
We disable the warning selectively for this particular case.
=> Disable unused warnings in TypeScript verification

aas_core_codegen/parse/_translate.py
We disallow the prefix `mutable` in the names of properties and methods to protect the code generation in languages such as C++ which distinguish between const and mutating getters.
=> Disallow `mutable` prefix in property and methods

requirements.txt
In one of the merges from ``v3`` development branch, we forgot to add the module ``greenery`` to the requirements. (Possibly in #352, but we are not sure.)
=> Add greenery to requirements

aas_core_codegen/csharp/structure/_generate.py, test_data/csharp/test_main/aas_core_meta.v3/expected_output/types.cs
We change the order of modifiers (``new`` later) to satisfy InspectCode.
=> Fix order of modifiers in strengthening in C#

continuous_integration/mypy.ini
Since the module ``greenery`` from the requirements comes without type annotations, we exclude it from the mypy checks.
=> Exclude ``greenery`` from mypy

aas_core_codegen/infer_for_schema/_inline.py, test_data/jsonschema/test_main/aas_core_meta.v3/expected_output/schema.json, test_data/rdf_shacl/test_main/expected/aas_core_meta.v3/expected_output/shacl-schema.ttl
We infer the constraints from properties typed as constrained primitives only if they are specified for that particular class *and* the property is not a non-nullability strengthening. We can do that as non-nullability strengthenings do not affect constraints inferred for the schemas.
=> Infer for schema only from non-strengthened props

aas_core_codegen/infer_for_schema/_inline.py, aas_core_codegen/intermediate/__init__.py, aas_core_codegen/intermediate/_types.py
We refactor the check to a separate function for better readability.
=> Refactor non-nullability strengthening check

aas_core_codegen/python/description.py, aas_core_codegen/python/structure/_generate.py, test_data/python/test_main/aas_core_meta.v3/expected_output/types.py
We make a couple of minor formatting fixes in the code generation to satisfy pylint on generated code.
=> Fix Python gen for pylint

aas_core_codegen/jsonschema/main.py, test_data/jsonschema/test_main/aas_core_meta.v3/expected_output/schema.json
We added redundant definitions of `modelType` property in JSON schema, and remove them in this patch.
=> Skip model type in descendants in JSON schema

aas_core_codegen/csharp/enhancing/_generate.py, test_data/csharp/test_main/aas_core_meta.v3/expected_output/enhancing.cs
Currently, you can only specify the unwrapping if you also specify the wrapping. This is unfortunate, as wrapping might occur in a different part of the code base from where you define the unwrapping.
In particular, the enhancer needs an enhancement factory -- which might not be available at the time of unwrapping.
Therefore, we refactor the unwrapping bits from the enhancer.
=> Refactor unwrapper from enhancer in C#

aas_core_codegen/csharp/xmlization/_generate.py, test_data/csharp/test_main/aas_core_meta.v3/expected_output/xmlization.cs
Currently, we break out of the loop when parsing sequences of XML elements representing properties of an instances. This gives misleading error messages ("required property not set").
Instead, with this patch, we report that the text is unexpected, which is much clearer to the user.
=> Report unexpected text in XML sequences in C#

aas_core_codegen/naming.py, aas_core_codegen/python/naming.py
We refactor the pascal casing to module `aas_core_codegen.naming` from Python generator so that the feature can be used in other modules as well.
=> Refactor pascal case in `naming`

aas_core_codegen/csharp/visitation/_generate.py, test_data/csharp/test_main/aas_core_meta.v3/expected_output/visitation.cs
We eventually noticed that the `Visit` and `Transform` methods can not be overridden in the implementors of the respective visitors and transformers as they were not marked as `virtual`.
=> Make visitation dispatches virtual in C#

aas_core_codegen/python/verification/_generate.py, test_data/python/test_main/aas_core_meta.v3/expected_output/verification.py
We add the `__repr__` method to the verification error in order to facilitate debugging in the downstream applications.
See: https://github.com/aas-core-works/aas-core3.0-python/issues/11
=> Add `__repr__` to verification errors in Python

aas_core_codegen/typescript/verification/_generate.py, test_data/typescript/test_main/aas_core_meta.v3/expected_output/verification.ts
We disable the linter rule for double negations in the generated verification module since double negations are deliberately generated. Namely, we do check if a constraint is violated with "if not constraint fulfilled". If the constraint is formulated as a NAND, it will result in a (desired) double negation.
=> Disable linting double negations in TypeScript

requirements.txt
We need to upgrade greenery to 4.1.0 so that we can merge regex patterns using character classes.
See: https://github.com/qntm/greenery/issues/81
=> Upgrade greenery to 4.1.0

aas_core_codegen/typescript/verification/_generate.py
We mistakenly forgot to remove the string interpolation in a string in typescript verification generator.
=> Remove redundant string interpolation

aas_core_codegen/csharp/copying/_generate.py, aas_core_codegen/csharp/enhancing/_generate.py, aas_core_codegen/csharp/jsonization/_generate.py, aas_core_codegen/csharp/stringification/_generate.py, aas_core_codegen/csharp/verification/_generate.py, aas_core_codegen/csharp/visitation/_generate.py, aas_core_codegen/csharp/xmlization/_generate.py, aas_core_codegen/golang/jsonization/_generate.py, aas_core_codegen/golang/stringification/_generate.py, aas_core_codegen/golang/structure/_generate.py, aas_core_codegen/infer_for_schema/_inline.py, aas_core_codegen/intermediate/_translate.py, aas_core_codegen/intermediate/_types.py, aas_core_codegen/jsonschema/main.py, aas_core_codegen/python/stringification/_generate.py, aas_core_codegen/python/structure/_generate.py, aas_core_codegen/python/verification/_generate.py, aas_core_codegen/python/xmlization/_generate.py, aas_core_codegen/smoke/main.py, aas_core_codegen/typescript/jsonization/_generate.py, aas_core_codegen/typescript/stringification/_generate.py, aas_core_codegen/typescript/structure/_generate.py, aas_core_codegen/typescript/verification/_generate.py
We pre-compute lists for classes in #406, so we simplify the code in this patch to make it more correct by design and more readable.
However, we made no changes to the code which would change the order of iteration over the symbols, and consequently changing the test data. This would cause too many changes to the downstream code which we did not consider worthwhile just for the sake of code consistency.
=> Simplify iterations over our types using lists

aas_core_codegen/intermediate/__init__.py
We forgot to include `intermediate._types.Constant` in `intermediate` due to an unintentional omission.
=> Expose `intermediate.Constant`

aas_core_codegen/python/unrolling.py, aas_core_codegen/typescript/unrolling.py
Pylint does not accept unsude import and it is necessary for the GitHub actions.
=> Remove an unused import

aas_core_codegen/jsonld/main.py
We import `assert_never` from `common` module for compatibility with other Python versions.
=> Fix `assert_never` import in JSON-LD generator

aas_core_codegen/csharp/xmlization/_generate.py, test_data/csharp/test_main/aas_core_meta.v3/expected_output/xmlization.cs
When we encountered XML declarations, we threw exceptions with uninformative messages. Namely, we expect the reader to be moved to the content, but most users omitted to read that in the documentation.
We refine the error message for this particular situation, and hint at `MoveToContent` method on the reader.
See [this aas-core3.0-csharp issue] for more details.
[this aas-core3.0-csharp issue]: https://github.com/aas-core-works/aas-core3.0-csharp/issues/24
=> Fix error message in C# xmlization on declarations

aas_core_codegen/jsonld/main.py, test_data/jsonld_context/context.jsonld
We specify `"@container": "@set"` when it is needed in JSON LD.
Additionally, we also patch a minor issue related to predicate URIs
inconsistent with other schemas.
=> Add `"@container": "@set"` and fix URIs in JSON LD

aas_core_codegen/common.py, aas_core_codegen/yielding/__init__.py, aas_core_codegen/yielding/flow.py, aas_core_codegen/yielding/linear.py, tests/yielding/test_linear.py
We model the abstract control flow of co-routines so that we can transpile them into state machines for languages which do not support them natively. In particular, this is necessary when we want to model iterations over unmaterialized sequences such as verification errors.
=> Transpile yielding, i.e., co-routines

aas_core_codegen/csharp/enhancing/_generate.py
We omitted by mistake to emit the specific implementation for the enhanced class code.
=> Fix missed code emitting in C# enhancer

README.rst
The generated code and schemas are indeed stable, since they are now officially adopted by IDTA. Hence, we remove the misleading warning in the readme.
Fixes #429.
=> Remove stability warning from Readme

test_data/cpp/test_main/aas_core_meta.v3/expected_output/enhancing.hpp
We mistakenly forgot to remove a curly bracket when removing string interpolation in C++ generator.
=> Remove redundant curly bracked in C++

aas_core_codegen/csharp/common.py, aas_core_codegen/csharp/structure/_generate.py, aas_core_codegen/intermediate/_translate.py, aas_core_codegen/intermediate/pattern_verification.py, aas_core_codegen/main.py, aas_core_codegen/parse/_translate.py, aas_core_codegen/smoke/main.py
As we have long released the aas-core-codegen in the wild, there is no point of keeping a todo comments. At this point in time, we deprioritize tests that we planned in the beginning.
=> Remove `BEFORE-RELEASE` comments

aas_core_codegen/typescript/stringification/_generate.py, aas_core_codegen/typescript/structure/_generate.py, test_data/typescript/test_main/aas_core_meta.v3/expected_output/stringification.ts, test_data/typescript/test_main/aas_core_meta.v3/expected_output/types.ts
We add a function `modelType` to `Class` interface in TypeScript so that users can retrieve the runtime type of an instance.
Fixes https://github.com/aas-core-works/aas-core3.0-typescript/issues/15.
=> Indicate runtime model type in TypeScript

tests/jsonld_context/test_main.py
A `breakpoint()` has been mistakenly left in the json-ld test. In particular, the breakpoint put the update script for aas-core-meta on hold.
In this patch, we remove the breakpoint so that the tests can run again.
=> Remove breakpoint in json-ld tests

dev_scripts/update_to_aas_core_meta.py
It turned out that a test script blocked in the update-to-aas-core-meta development script, but the current version of the script only listed the number of running scripts, and not which script was blocking.
In this patch, we explicitly lists which tests are still running after the initial expected runtime, so that the developer can take action if needed.
=> Report running tests in update-to-meta script

aas_core_codegen/cpp/aas_common/_generate.py, dev_scripts/replace-curly-brackets-backslashes-and-two-space-indent.html, test_data/cpp/test_main/aas_core_meta.v3/expected_output/common.cpp
We fix the C++ generator so that the generator code passes all the tests related to jsonization of concrete classes.
=> Fix C++ to pass jsonization of concrete classes

aas_core_codegen/cpp/stringification/_generate.py, aas_core_codegen/cpp/wstringification/_generate.py, test_data/cpp/test_main/aas_core_meta.v3/expected_output/stringification.cpp, test_data/cpp/test_main/aas_core_meta.v3/expected_output/wstringification.cpp
We fix all the bugs in the C++ generator so that the tests now pass.
=> Fix c++ stringification of enums

aas_core_codegen/python/xmlization/_generate.py, test_data/python/test_main/aas_core_meta.v3/expected_output/xmlization.py
Since the XMLPullParser doesn't guarantee that the attributes of a start events are populated. When the parser has not yet encountered the text event, this attribute will be None. Instead we additionally have to check end events, as well.
=> Fix missing text in element error for Python

test_data/cpp/test_main/aas_core_meta.v3/expected_output/verification.cpp, test_data/cpp/test_main/aas_core_meta.v3/expected_output/verification.hpp, test_data/cpp/test_main/aas_core_meta.v3/input/snippets/verification/is_xs_date_time_UTC.cpp, test_data/cpp/test_main/aas_core_meta.v3/input/snippets/verification/is_xs_date_time_UTC.hpp, test_data/cpp/test_main/aas_core_meta.v3/input/snippets/verification/value_consistent_with_XSD_type.cpp, test_data/cpp/test_main/aas_core_meta.v3/input/snippets/verification/value_consistent_with_XSD_type.hpp
We make the logical checks for XSD data types public, so that the clients can check their structures in a fine-grained manner.
=> Make some verification functions public in C++

aas_core_codegen/cpp/xmlization/_generate.py, test_data/cpp/test_main/aas_core_meta.v3/expected_output/xmlization.cpp
We fix the C++ generated code so that the empty lists are correctly accepted, *i.e.*, we treat closing empty list properties as empty lists.
=> Fix generated C++ to handle empty lists in XML

aas_core_codegen/jsonld/main.py, test_data/jsonld_context/aas_core_meta.v3/output/context.jsonld, test_data/jsonld_context/context.jsonld
This PR is related to https://github.com/admin-shell-io/aas-specs/issues/386.
It adds a wrapping "@context" tag around the JSON-LD context.
It is needed so that the context can be served directly at a given URL and digested in a JSON-LD document.
=> Add a wrapping `@context` tag to JSON-LD generator

tests/jsonld_context/test_main.py
We have to specify the encoding explicitly at reading in the unit tests since the encoding is not UTF-8 by default on some Windows versions.
=> Fix encoding in JSON-LD tests

AUTHORS
We add Markus Böhm as contributor for conplement AG and correct the spelling of conplement AG.
=> Fix `AUTHORS` for conplement AG

aas_core_codegen/java/generation/_generate.py, test_data/java/test_main/aas_core_meta.v3/expected_output/generation/AdministrativeInformationBuilder.java, test_data/java/test_main/aas_core_meta.v3/expected_output/generation/AnnotatedRelationshipElementBuilder.java, test_data/java/test_main/aas_core_meta.v3/expected_output/generation/AssetAdministrationShellBuilder.java, test_data/java/test_main/aas_core_meta.v3/expected_output/generation/AssetInformationBuilder.java, test_data/java/test_main/aas_core_meta.v3/expected_output/generation/BasicEventElementBuilder.java, test_data/java/test_main/aas_core_meta.v3/expected_output/generation/BlobBuilder.java, test_data/java/test_main/aas_core_meta.v3/expected_output/generation/CapabilityBuilder.java, test_data/java/test_main/aas_core_meta.v3/expected_output/generation/ConceptDescriptionBuilder.java, test_data/java/test_main/aas_core_meta.v3/expected_output/generation/DataSpecificationIec61360Builder.java, test_data/java/test_main/aas_core_meta.v3/expected_output/generation/EmbeddedDataSpecificationBuilder.java, test_data/java/test_main/aas_core_meta.v3/expected_output/generation/EntityBuilder.java, test_data/java/test_main/aas_core_meta.v3/expected_output/generation/EnvironmentBuilder.java, test_data/java/test_main/aas_core_meta.v3/expected_output/generation/EventPayloadBuilder.java, test_data/java/test_main/aas_core_meta.v3/expected_output/generation/ExtensionBuilder.java, test_data/java/test_main/aas_core_meta.v3/expected_output/generation/FileBuilder.java, test_data/java/test_main/aas_core_meta.v3/expected_output/generation/MultiLanguagePropertyBuilder.java, test_data/java/test_main/aas_core_meta.v3/expected_output/generation/OperationBuilder.java, test_data/java/test_main/aas_core_meta.v3/expected_output/generation/PropertyBuilder.java, test_data/java/test_main/aas_core_meta.v3/expected_output/generation/QualifierBuilder.java, test_data/java/test_main/aas_core_meta.v3/expected_output/generation/RangeBuilder.java, test_data/java/test_main/aas_core_meta.v3/expected_output/generation/ReferenceBuilder.java, test_data/java/test_main/aas_core_meta.v3/expected_output/generation/ReferenceElementBuilder.java, test_data/java/test_main/aas_core_meta.v3/expected_output/generation/RelationshipElementBuilder.java, test_data/java/test_main/aas_core_meta.v3/expected_output/generation/ResourceBuilder.java, test_data/java/test_main/aas_core_meta.v3/expected_output/generation/SpecificAssetIdBuilder.java, test_data/java/test_main/aas_core_meta.v3/expected_output/generation/SubmodelBuilder.java, test_data/java/test_main/aas_core_meta.v3/expected_output/generation/SubmodelElementCollectionBuilder.java, test_data/java/test_main/aas_core_meta.v3/expected_output/generation/SubmodelElementListBuilder.java
We fix the generated setter names in the Java builder classes so that they match the expected camel case convention. Until now, the setter names are erroneously printed in lower case.
=> Fix setter names for Java builder classes

AUTHORS
The authors added in #482 supplied no commits. While they did contribute to the project with ideas and suggestions, they did not contribute any changes to the code or content of this repository. Since `AUTHORS` concerns the copyright of the content, and not the acknowledgments, we revert the changes in #482.
At this point, we do warmly acknowledge their contributions in ideas and discussions!
=> Revert #482 due to a misunderstanding

README.rst, aas_core_codegen/jsonschema/main.py, aas_core_codegen/parse/retree/_parse.py, test_data/java/test_main/aas_core_meta.v3/expected_output/xmlization/Xmlization.java, test_data/jsonschema/test_main/aas_core_meta.v3/expected_output/schema.json, tests/our_jsonschema/test_main.py
The escaping logic for patterns in JSON schema got convoluted, and we introduced inadvertently inconcistencies in the formatting. Namely, we first *unescaped* all the characters before passing them into the parser for regular expressions. This unescaped characters later propagated and mixed with *escaped* characters when the expression was transpiled for UTF-16.
To solve this mess, we remove the unescaping step at the beginning and test more thouroughly to specify & observe the expected behavior.
Fixes #485.
=> Fix escaping in JSON schema patterns

aas_core_codegen/golang/xmlization/_generate.py, test_data/golang/test_main/aas_core_meta.v3/expected_output/xmlization/xmlization.go
We read a token too much in `unmarshalXxx` functions. The bug went unnoticed as all our examples used indented XML, which eclipsed the over-consumption.
In this patch, we do not generate the `unmarshalXxx`, as they turn out to be redundant, and use `readXxxWithLookahead` to appropriately read the tokens without over-consumption.
=> Fix over-consuming XML de-serialization in Golang

aas_core_codegen/golang/jsonization/_generate.py, test_data/golang/test_main/aas_core_meta.v3/expected_output/jsonization/jsonization.go
We returned a concrete error pointer in the generated Golang code, which can cause various bugs, see [this page in Golang documentation].
Instead, we generate the code such that only abstract `error`'s are returned.
[this page in Golang documentation]: https://go.dev/doc/faq#nil_error
=> Return abstract errors in Golang

.github/workflows/ci.yml, setup.py
We include Python 3.11 and 3.12 in the CI to make sure everything runs on those Python versions as well.
Related issues: #491 and #492
=> Add support for Python 3.11 and 3.12

aas_core_codegen/intermediate/_translate.py, test_data/csharp/test_verification/builtin_functions/len/on_list/meta_model.py, test_data/intermediate/unexpected/invariant/unexpected_argument_count_to_len/meta_model.py
So far, we only checked in the translation phase that the names and the order of the properties and the constructor arguments match. In this change, we also check that they match in type annotations, which is the assumption we make in many code generators.
=> Check matching between properties and constructors

aas_core_codegen/parse/_translate.py
We exclude the keyword ``result`` from the list of the check for reserved keywords in the translation phase. The keyword is already a part of the AAS Server specification, so we can not roll back on this one, unfortunately.
=> Exclude Eiffel's keyword ``result``

aas_core_codegen/intermediate/_translate.py, test_data/csharp/test_verification/pattern_verification/utf32_as_literal/in_union/expected_verification.cs, test_data/csharp/test_verification/pattern_verification/utf32_as_literal/in_union/meta_model.py, tests/csharp/test_description.py, tests/infer_for_schema/test_patterns_on_properties.py, tests/infer_for_schema/test_patterns_on_self.py
As we transpile to some of the systems which always expect the regular expressions to be anchored at the start and the end (*e.g.*, XSD engines), we verify in the patch that all verification patterns are appropriately anchored. This ensures that the patterns will also be correctly transpiled down the line.
=> Verify that patterns are anchored

aas_core_codegen/parse/retree/__init__.py, aas_core_codegen/parse/retree/_fix.py, aas_core_codegen/parse/retree/_visitor.py, aas_core_codegen/xsd/main.py
We rename `parse.retree.BaseVisitor` to `PassThroughVisitor` in alignment with the naming used for the generated SDKs. The name "base visitor" is also a bit of a misnomer as it insinuates some kind of an abstract class, while the pass-through visitor is explicitly a concrete class.
=> Rename `parse.retree.BaseVisitor` to pass-through

aas_core_codegen/parse/retree/_parse.py
The overlapping ranges in regular expressions can hurt performance, so we explicitly check that no ranges overlap in the pattern verification functions.
=> Ensure no overlapping ranges in patterns

aas_core_codegen/cpp/verification/_generate.py, test_data/cpp/test_main/aas_core_meta.v3/expected_output/verification.cpp
We forgot to put a yield when iterating over the verification errors related to the root instance. We fix the issue in this change.
=> Fix non-recursive verification in C++

test_data/cpp/test_main/aas_core_meta.v3/expected_output/revm.cpp, test_data/cpp/test_main/aas_core_meta.v3/expected_output/revm.hpp
We are having trouble with CI on GitHub as it takes a lot of time. The previous run on #504 revealed only much later that we forgot to re-generate the test data. In this patch, we re-generate the test data with the trailing spaces removed.
=> Remove trailing space from test data

aas_core_codegen/python/jsonization/_generate.py, test_data/python/test_main/aas_core_meta.v3/expected_output/jsonization.py
We introduce an explicit check that the parsed object is indeed an array-like object instead of simply checking for an iterable as mappings are also iterables in Python.
=> Check for array-iness in Python de-jsonization

aas_core_codegen/python/jsonization/_generate.py, test_data/python/test_main/aas_core_meta.v3/expected_output/jsonization.py
We add an explicit check for missing ``modelType`` in generated Python code to account for the case where a concrete class without descendants needs a model type for backwards compatibility even though the model type property is redundant.
=> Check explicitly for ``modelType`` in Python

aas_core_codegen/python/jsonization/_generate.py, test_data/python/test_main/aas_core_meta.v3/expected_output/jsonization.py
We explicitly check in the generated Python code that the concrete classes without descendants which have a ``modelType`` defined in the de-serialization for backwards compatibility also specify a valid and expected ``modelType`` in JSON de-serialization.
=> Check explicitly for invalid model type in Python

aas_core_codegen/csharp/jsonization/_generate.py, aas_core_codegen/naming.py, test_data/csharp/test_main/aas_core_meta.v3/expected_output/jsonization.cs
Please see #510 for more details. This is a fix particularly for C# generation.
=> Check explicitly for invalid model type in C#

aas_core_codegen/golang/jsonization/_generate.py, test_data/golang/test_main/aas_core_meta.v3/expected_output/jsonization/jsonization.go
We erroneously copy-pasted the error message from the function for de-serialization of booleans to the function for de-serialization of strings, misleading the user of the generated code.
=> Fix error message in Go de-jsonization of strings

aas_core_codegen/golang/jsonization/_generate.py, test_data/golang/test_main/aas_core_meta.v3/expected_output/jsonization/jsonization.go
Please see #510 for more details. This is a fix particularly for Go generation.
=> Check explicitly for invalid model type in Go

aas_core_codegen/cpp/jsonization/_generate.py, test_data/cpp/test_main/aas_core_meta.v3/expected_output/jsonization.cpp
Please see #510 for more details. This is a fix particularly for C++ generation.
=> Check explicitly for invalid model type in C++

aas_core_codegen/java/jsonization/_generate.py, test_data/java/test_main/aas_core_meta.v3/expected_output/jsonization/Jsonization.java
Please see #510 for more details. This is a fix particularly for Java generation.
=> Check explicitly for invalid model type in Java

aas_core_codegen/jsonschema/main.py, aas_core_codegen/rdf_shacl/shacl.py, test_data/rdf_shacl/test_main/expected/aas_core_meta.v3/expected_output/shacl-schema.ttl, tests/our_jsonschema/test_main.py
We included the regex pattern as-is from the input which caused problems with the regex engines as the patterns in the meta-model are written in a Python dialect (and assuming that the regex engine works on UTF-32 characters). However, most regex engines in the wild operating on SHACL (*e.g.*, Java SHACL validators) use UTF-16 to represent the text and do not support some parts of the Python regex dialect. For example, in the input meta-model specification, we omit the minimum bound 0 (*e.g.*, ``{,4}``), which breaks with the Java regex engine beneath the SHACL validator.
Instead, with this patch, we parse the pattern from the specification and re-render it into the form that we also use in JSON Schema. We pick JSON Schema regex dialect as most SHACL validators in the wild can deal with …
=> Make SHACL regex patterns follow JSON Schema ones

setup.py, test_data/cpp/test_main/aas_core_meta.v3/expected_output/verification.cpp, test_data/csharp/test_main/aas_core_meta.v3/expected_output/verification.cs, test_data/golang/test_main/aas_core_meta.v3/expected_output/verification/verification.go, test_data/intermediate/real_meta_models/aas_core_meta.v3/expected_symbol_table.txt, test_data/java/test_main/aas_core_meta.v3/expected_output/verification/Verification.java, test_data/parse/real_meta_models/aas_core_meta.v3/expected_symbol_table.txt, test_data/python/test_main/aas_core_meta.v3/expected_output/verification.py, test_data/typescript/test_main/aas_core_meta.v3/expected_output/verification.ts
We update the development requirements to and re-record the test data for [aas-core-meta bd56058].
Notably, we propagate the fix for AASd-109 in V3.0 where we change the invariant such that it checks for consistency among properties even when a ``value`` property is missing. This affects only the re-recording of the test data corresponding to V3.0 meta-model.
[aas-core-meta bd56058]: https://github.com/aas-core-works/aas-core-meta/commit/bd56058
=> Update test data to aas-core-meta bd56058

setup.py, test_data/cpp/test_main/aas_core_meta.v3/expected_output/verification.cpp, test_data/csharp/test_main/aas_core_meta.v3/expected_output/verification.cs, test_data/golang/test_main/aas_core_meta.v3/expected_output/verification/verification.go, test_data/intermediate/real_meta_models/aas_core_meta.v3/expected_symbol_table.txt, test_data/java/test_main/aas_core_meta.v3/expected_output/verification/Verification.java, test_data/parse/real_meta_models/aas_core_meta.v3/expected_symbol_table.txt, test_data/python/test_main/aas_core_meta.v3/expected_output/verification.py, test_data/typescript/test_main/aas_core_meta.v3/expected_output/verification.ts
We update the development requirements to and re-record the test data for [aas-core-meta 35aa2cc].
Notably, we propagate the fix for V3.0 in the meta-model of Constraint AASd-109 for type inference as we erroneously included a non-nullness check for a non-optional attribute (``type_value_list_element``).
[aas-core-meta 35aa2cc]: https://github.com/aas-core-works/aas-core-meta/commit/35aa2cc
=> Update test data to aas-core-meta 35aa2cc

aas_core_codegen/cpp/verification/_generate.py, aas_core_codegen/csharp/verification/_generate.py, aas_core_codegen/golang/verification/_generate.py, aas_core_codegen/intermediate/type_inference.py, aas_core_codegen/java/optional.py, aas_core_codegen/java/verification/_generate.py, aas_core_codegen/python/verification/_generate.py, aas_core_codegen/typescript/verification/_generate.py, tests/intermediate/test_type_inference.py
So far, we were unsure what the best abstraction for type inference would be. After a couple of code generators, the structure for the type inference crystalized out: we refactor it into two functions, one for the class invariants and one for the transpilable verification functions.
The type inference for pattern verification functions is explicitly left out as we can not infer the type of the matching result in any meaningful way with the simple types we have so far, and we also do not need to. Namely, we ensure that pattern verification functions follow a very strict structure where each variable can only be a string in the parsing stage.
=> Refactor type inference in functions

aas_core_codegen/cpp/transpilation.py, aas_core_codegen/cpp/verification/_generate.py, aas_core_codegen/intermediate/type_inference.py, test_data/cpp/test_main/aas_core_meta.v3/expected_output/verification.cpp, tests/common.py, tests/cpp/test_verification.py, tests/intermediate/test_type_inference.py
We extend the type inference to, correctly, consider the case with disjunctions (``or``) with nullness checks (``is None``).
For example, ``(A is None) or (A == 3)`` means that the first value in the disjunction (``A is None``) implies that ``A`` is non-null in the second value (``A == 3``).
=> Fix type inference for disjunctions with nullness

aas_core_codegen/csharp/jsonization/_generate.py, test_data/csharp/test_main/aas_core_meta.v3/expected_output/jsonization.cs
We explicitly check that both optional and required properties can not be set to ``null``. The optional properties should be explicitly absent from the object by specification, and thus ``null`` is not an acceptable value for optional properties.
=> Explicitly check for null values in C# jsonization

aas_core_codegen/protobuf/structure/_generate.py, test_data/proto/test_main/expected/aas_core_meta.v3/expected_output/types.proto, test_data/proto/test_main/expected/abstract_and_concrete_classes/expected_output/types.proto, test_data/proto/test_main/expected/concrete_class_with_primitive_attributes/expected_output/types.proto
Previously, we relied on the order of ``set`` for the fields in Protobuf. This is dangerous as the order of ``set`` is not well-defined across different Python versions and implementations.
To avoid potential bugs in the future, we fix the fields to correspond with the order of properties in the class.
Note that this solution is also not completely future proof. If you add properties in the middle of a class, the field IDs in protocol buffers will change causing incompatibility between the two Protocol Buffer definitions.
=> Fix the order of fields in Protobuf

aas_core_codegen/protobuf/common.py, aas_core_codegen/protobuf/structure/_generate.py
We hastly merged in the changes in the previous pull requests. This patch fixes the CI errors.
=> Fix CI errors

aas_core_codegen/python/xmlization/_generate.py, test_data/python/test_main/aas_core_meta.v3/expected_output/xmlization.py
We generate additional functions which can de-serialize all model instance by determining the type based on the first start element and dispatching to the concrete de-serialization function accordingly.
=> Add general XML de-serialization to Python

aas_core_codegen/intermediate/_translate.py, test_data/intermediate/unexpected/optional_constructor_arguments_wo_default/default_non_none/expected_error.txt, test_data/intermediate/unexpected/optional_constructor_arguments_wo_default/default_non_none/meta_model.py, test_data/intermediate/unexpected/optional_constructor_arguments_wo_default/no_default/expected_error.txt, test_data/intermediate/unexpected/optional_constructor_arguments_wo_default/no_default/meta_model.py, test_data/opcua/test_main/concrete_class_with_enum/meta_model.py, test_data/opcua/test_main/concrete_class_with_list_of_instances/meta_model.py, test_data/opcua/test_main/concrete_class_with_primitive_attributes/meta_model.py, test_data/proto/test_main/expected/concrete_class_with_enum/meta_model.py, test_data/proto/test_main/expected/concrete_class_with_list_of_instances/meta_model.py, test_data/proto/test_main/expected/concrete_class_with_primitive_attributes/meta_model.py, test_data/python_protobuf/test_main/concrete_class_with_enum/meta_model.py, test_data/python_protobuf/test_main/concrete_class_with_list_of_instances/meta_model.py, test_data/python_protobuf/test_main/concrete_class_with_primitive_attributes/meta_model.py, test_data/rdf_shacl/test_main/unexpected/regression_len_constraint_on_class_property/expected_output/stderr.txt, tests/proto/test_main.py
We enforce that all optional constructor arguments must be given a ``None`` default value for consistency. We struggled in downstream projects where optional arguments *without* a default caused a lot of confusion.
Therefore, to make the life of the downstream users simpler (*e.g.*, people using the generated SDKs), we impose that all constructor arguments must be initialized with a ``None`` default, which is in line with expectations of most of the programmers.
=> Enforce None default for optional constructor args

dev_scripts/update_to_aas_core_meta.py, tests/jsonld_context/test_main.py
We perform a series of fixes to the dev script revealed by updating to the latest aas-core-meta.
The errors were caused by the bit rot.
=> Fix update-to-aas-core-meta dev script

setup.py, test_data/cpp/test_main/aas_core_meta.v3/expected_output/verification.cpp, test_data/cpp/test_main/aas_core_meta.v3/expected_output/verification.hpp, test_data/csharp/test_main/aas_core_meta.v3/expected_output/verification.cs, test_data/golang/test_main/aas_core_meta.v3/expected_output/verification/verification.go, test_data/intermediate/real_meta_models/aas_core_meta.v3/expected_symbol_table.txt, test_data/java/test_main/aas_core_meta.v3/expected_output/verification/Verification.java, test_data/jsonld_context/aas_core_meta.v3/output/context.jsonld, test_data/jsonschema/test_main/aas_core_meta.v3/expected_output/schema.json, test_data/opcua/test_main/aas_core_meta.v3/expected_output/nodeset.xml, test_data/parse/real_meta_models/aas_core_meta.v3/expected_symbol_table.txt, test_data/python/test_main/aas_core_meta.v3/expected_output/verification.py, test_data/rdf_shacl/test_main/expected/aas_core_meta.v3/expected_output/shacl-schema.ttl, test_data/typescript/test_main/aas_core_meta.v3/expected_output/verification.ts
We update the development requirements to and re-record the test data for [aas-core-meta f2fd738].
Notably, we propagate the latest fixes for V3.0.2 from aas-core-meta.
[aas-core-meta f2fd738]: https://github.com/aas-core-works/aas-core-meta/commit/f2fd738
=> Update test data to aas-core-meta f2fd738

.github/workflows/ci.yml, setup.py
We deprecate Python 3.8 as it reached the end of life on 7th October 2024.
=> Deprecate Python 3.8
