aas-core-works/aas-core-codegen

CONTRIBUTING.rst, README.rst
This patch includes a document to help new developers join the project.
=> Add CONTRIBUTING.rst

CHANGELOG.rst, aas_core_codegen/__init__.py, setup.py
* A post release to test the publishing pipeline.
=> Release 0.0.1rc1.post1

aas_core_codegen/csharp/jsonization/_generate.py, aas_core_codegen/intermediate/_translate.py, test_data/csharp/test_main/v3rc2/expected_output/jsonization.cs, test_data/intermediate/expected/class/inheritance/expected_symbol_table.txt, test_data/intermediate/expected/real_meta_models/v3rc2/expected_symbol_table.txt
There was a bug such that the descendants were actually ignored in the
second pass which should have properly resolved the inheritances.
This patch fixes the bug.
=> Fix second pass to resolve descendants correctly

aas_core_codegen/intermediate/_translate.py, aas_core_codegen/intermediate/pattern_verification.py
In this patch we improve the error messages reported when a
non-implementation-specific verification function could not be matched.
This is necessary so that the user can have a more fine-grained cause
why the matching failed.
Simply reporting that the function could not be matched did not work at
all.
=> Improve errors on unmatched verification functions

README.rst, aas_core_codegen/infer_for_schema/__init__.py, aas_core_codegen/infer_for_schema/_common.py, aas_core_codegen/infer_for_schema/_len.py, aas_core_codegen/infer_for_schema/_pattern.py, aas_core_codegen/infer_for_schema/_stringify.py, aas_core_codegen/intermediate/__init__.py, aas_core_codegen/intermediate/_translate.py, aas_core_codegen/intermediate/_types.py, aas_core_codegen/intermediate/pattern_verification.py, aas_core_codegen/jsonschema/__init__.py, aas_core_codegen/jsonschema/main.py, aas_core_codegen/main.py, test_data/jsonschema/test_main/v3rc2/expected_output/schema.json, test_data/jsonschema/test_main/v3rc2/expected_output/stdout.txt, test_data/jsonschema/test_main/v3rc2/input/meta_model.py, test_data/jsonschema/test_main/v3rc2/input/snippets/Lang_string_set.json, test_data/jsonschema/test_main/v3rc2/input/snippets/schema_base.json, tests/common.py, tests/infer_for_schema/test_len_on_properties.py, tests/infer_for_schema/test_len_on_self.py, tests/infer_for_schema/test_patterns_on_properties.py, tests/infer_for_schema/test_patterns_on_self.py, tests/jsonschema/test_main.py, tests/test_parse.py
This is a major change which introduces inferrence of constraints based
on the meta-model which can also be represented in a JSON schema (and in
other similiar schemas such as XSD).
=> Provide generator for JSON schema

continuous_integration/precommit.py
The terminal output is littered with the uninformative stack trace
when a command call in the ``precommit.py`` fails.
This patch wraps each command call such that we report a more succinct
message, and thus make running precommit checks in the IDE a bit more
user-friendly.
=> Avoid exceptions in precommit steps

README.rst, aas_core_codegen/infer_for_schema/_len.py, aas_core_codegen/main.py, aas_core_codegen/rdf_shacl/__init__.py, aas_core_codegen/rdf_shacl/_description.py, aas_core_codegen/rdf_shacl/common.py, aas_core_codegen/rdf_shacl/main.py, aas_core_codegen/rdf_shacl/naming.py, aas_core_codegen/rdf_shacl/rdf.py, aas_core_codegen/rdf_shacl/shacl.py, test_data/rdf_shacl/test_main/v3rc1/expected_output/rdf-ontology.ttl, test_data/rdf_shacl/test_main/v3rc1/expected_output/shacl-schema.ttl, test_data/rdf_shacl/test_main/v3rc1/expected_output/stdout.txt, test_data/rdf_shacl/test_main/v3rc1/input/meta_model.py, test_data/rdf_shacl/test_main/v3rc1/input/snippets/rdf/Lang_string_set/as_rdfs_range.ttl, test_data/rdf_shacl/test_main/v3rc1/input/snippets/rdf/Lang_string_set/owl_class.ttl, test_data/rdf_shacl/test_main/v3rc1/input/snippets/rdf/preamble.ttl, test_data/rdf_shacl/test_main/v3rc1/input/snippets/shacl/Lang_string_set/shape.ttl, test_data/rdf_shacl/test_main/v3rc1/input/snippets/shacl/preamble.ttl, test_data/rdf_shacl/test_main/v3rc1/input/snippets/url_prefix.txt, tests/rdf_shacl/test_common.py, tests/rdf_shacl/test_description.py, tests/rdf_shacl/test_main.py
We add a generator for RDF+SHACL schemas and test it based on V3RC01.
=> Generte RDF and SHACL schemas

aas_core_codegen/rdf_shacl/naming.py, aas_core_codegen/rdf_shacl/rdf.py, test_data/jsonschema/test_main/v3rc1/expected_output/schema.json, test_data/jsonschema/test_main/v3rc1/input/meta_model.py, test_data/rdf_shacl/test_main/v3rc1/expected_output/rdf-ontology.ttl, test_data/rdf_shacl/test_main/v3rc1/input/meta_model.py
This is a further iteration on approximation to the RDF specs in
github.com/admin-shell-io/aas-specs.
Additionally, we updated V3RC01 meta-model for JSON Schema as well since
we spotted a couple of inconsistencies with the book.
=> Approximate RDF to aas-specs

test_data/jsonschema/test_main/v3rc1/expected_output/schema.json, test_data/jsonschema/test_main/v3rc1/input/meta_model.py, test_data/rdf_shacl/test_main/v3rc1/expected_output/rdf-ontology.ttl, test_data/rdf_shacl/test_main/v3rc1/expected_output/shacl-schema.ttl, test_data/rdf_shacl/test_main/v3rc1/input/meta_model.py, tests/jsonschema/test_main.py
This patch comprises minor fixes that were discovered while diff'ing
against the official RDF schema.
=> Fix minor errors in test data for V3RC01

test_data/csharp/test_main/v3rc2/expected_output/jsonization.cs, test_data/csharp/test_main/v3rc2/expected_output/types.cs, test_data/csharp/test_main/v3rc2/expected_output/verification.cs, test_data/csharp/test_main/v3rc2/input/meta_model.py, test_data/jsonschema/test_main/v3rc1/input/meta_model.py, test_data/rdf_shacl/test_main/v3rc1/input/meta_model.py
This patch propagates back the latest meta-models from aas-core-meta to
the testing data.
=> Sync test data with aas-core-meta

test_data/jsonschema/test_main/v3rc1/expected_output/schema.json, test_data/jsonschema/test_main/v3rc1/input/meta_model.py, test_data/rdf_shacl/test_main/v3rc1/expected_output/rdf-ontology.ttl, test_data/rdf_shacl/test_main/v3rc1/expected_output/shacl-schema.ttl, test_data/rdf_shacl/test_main/v3rc1/input/meta_model.py
These are minor fixes after comparing against the JSON schema in
http://github.com/admin-shell-io/aas-specs.
=> Fix test data after diffing aas-specs JSON schema

test_data/jsonschema/test_main/v3rc1/expected_output/schema.json, test_data/jsonschema/test_main/v3rc1/input/meta_model.py, test_data/rdf_shacl/test_main/v3rc1/expected_output/rdf-ontology.ttl, test_data/rdf_shacl/test_main/v3rc1/expected_output/shacl-schema.ttl, test_data/rdf_shacl/test_main/v3rc1/input/meta_model.py
This is a batch of changes in the meta-model after reviewing official
RDF specs for V3RC01.
=> Update test data for V3RC01 after RDF review

aas_core_codegen/rdf_shacl/naming.py, aas_core_codegen/rdf_shacl/rdf.py, test_data/rdf_shacl/test_main/v3rc1/expected_output/rdf-ontology.ttl, test_data/rdf_shacl/test_main/v3rc1/expected_output/shacl-schema.ttl
This is a batch of minor changes to fix discrepancies detected while
reviewing the official RDF schema for V3RC01.
=> Update RDF gen after review of V3RC01

test_data/jsonschema/test_main/v3rc1/expected_output/schema.json, test_data/jsonschema/test_main/v3rc1/input/meta_model.py, test_data/jsonschema/test_main/v3rc1/input/snippets/Lang_string_set.json, test_data/jsonschema/test_main/v3rc1/input/snippets/schema_base.json, test_data/rdf_shacl/test_main/v3rc1/expected_output/rdf-ontology.ttl, test_data/rdf_shacl/test_main/v3rc1/expected_output/shacl-schema.ttl, test_data/rdf_shacl/test_main/v3rc1/input/meta_model.py
This is yet another batch of fixes for V3RC01 test data after reviewing
official JSON schema.
=> Fix once more test data for V3RC01

test_data/intermediate/expected/real_meta_models/v3rc2/expected_symbol_table.txt, test_data/intermediate/expected/real_meta_models/v3rc2/meta_model.py, test_data/jsonschema/test_main/v3rc2/expected_output/schema.json, test_data/jsonschema/test_main/v3rc2/input/meta_model.py, test_data/parse/expected/real_meta_models/v3rc2/expected_symbol_table.txt, test_data/parse/expected/real_meta_models/v3rc2/meta_model.py
Subtle discrepancies sneaked in during the development between different
meta-models for V3RC02. With this patch, we equalize all the meta-models
with aas-core-meta repository.
We expect more of such equalizations in the future as well.
=> Equalize test data for V3RC2

test_data/jsonschema/test_main/v3rc1/expected_output/schema.json, test_data/jsonschema/test_main/v3rc1/input/meta_model.py, test_data/rdf_shacl/test_main/v3rc1/expected_output/rdf-ontology.ttl, test_data/rdf_shacl/test_main/v3rc1/expected_output/shacl-schema.ttl, test_data/rdf_shacl/test_main/v3rc1/input/meta_model.py
We reviewed the "official" SHACL schema for V3RC01 and propagated back
the resolved differences to our test data.
=> Update test data for V3RC01 after SHACL review

test_data/jsonschema/test_main/v3rc1/expected_output/schema.json, test_data/jsonschema/test_main/v3rc1/input/meta_model.py, test_data/rdf_shacl/test_main/v3rc1/expected_output/shacl-schema.ttl, test_data/rdf_shacl/test_main/v3rc1/input/meta_model.py
We synchronize our test data for V3RC01 with aas-core-meta repository
after various fixes were made.
=> Propagate postfixes from aas-core-meta

continuous_integration/precommit.py
We had a couple of glitches where we forgot to keep the test
meta-models in sync. This patch adds a check in the pre-commit script so
that we can automatically ensure that a subset of test meta-models is
in itself identical.
=> Check in precommit for identical test meta-models

test_data/jsonschema/test_main/v3rc1/expected_output/schema.json, test_data/jsonschema/test_main/v3rc1/input/meta_model.py, test_data/rdf_shacl/test_main/v3rc1/expected_output/rdf-ontology.ttl, test_data/rdf_shacl/test_main/v3rc1/expected_output/shacl-schema.ttl, test_data/rdf_shacl/test_main/v3rc1/input/meta_model.py
We propagate back the fixes from aas-core-meta after going over the
book.
=> Fix data specifications in V3RC01

test_data/jsonschema/test_main/v3rc1/expected_output/schema.json, test_data/jsonschema/test_main/v3rc1/input/meta_model.py, test_data/rdf_shacl/test_main/v3rc1/expected_output/rdf-ontology.ttl, test_data/rdf_shacl/test_main/v3rc1/expected_output/shacl-schema.ttl, test_data/rdf_shacl/test_main/v3rc1/input/meta_model.py
This patch is a mere propagation of fixes from aas-core-meta repository.
=> Propagate fixes of V3RC01 from aas-core-meta

.idea/dictionaries/rist.xml, aas_core_codegen/rdf_shacl/rdf.py, aas_core_codegen/rdf_shacl/shacl.py, test_data/rdf_shacl/test_main/v3rc1/expected_output/shacl-schema.ttl, test_data/rdf_shacl/test_main/v3rc1/input/snippets/shacl/preamble.ttl
This patch includes all the minor changes which were necessary to come
as close as possible to the "official" SHACL schema for V3RC01.
=> Approximate to official SHACL for V3RC01

test_data/csharp/test_main/v3rc2/expected_output/jsonization.cs, test_data/csharp/test_main/v3rc2/expected_output/types.cs, test_data/csharp/test_main/v3rc2/expected_output/verification.cs, test_data/csharp/test_main/v3rc2/input/meta_model.py, test_data/intermediate/expected/real_meta_models/v3rc2/expected_symbol_table.txt, test_data/intermediate/expected/real_meta_models/v3rc2/meta_model.py, test_data/jsonschema/test_main/v3rc1/expected_output/schema.json, test_data/jsonschema/test_main/v3rc1/input/meta_model.py, test_data/jsonschema/test_main/v3rc2/expected_output/schema.json, test_data/jsonschema/test_main/v3rc2/input/meta_model.py, test_data/parse/expected/real_meta_models/v3rc2/expected_symbol_table.txt, test_data/parse/expected/real_meta_models/v3rc2/meta_model.py, test_data/rdf_shacl/test_main/v3rc1/input/meta_model.py
We propagate back meta-models from aas-core-meta repository back to our
test data.
=> Perform back-propagation from aas-core-meta

aas_core_codegen/csharp/jsonization/_generate.py, test_data/csharp/test_main/v3rc2/expected_output/jsonization.cs
Currently, we generate "kind of" XPaths for reporting the errors in JSON
de/serialization.
With this patch, we generate proper JSON paths instead, which also
support proper escaping and are more familiar to developers working with
JSON.
=> Generate JSON paths for C# jsonization errors

aas_core_codegen/intermediate/_translate.py
PyCharm is a bit stricter than mypy so a couple of (potential) typing
issues and typos went unnoticed. This change fixes them.
=> Fix minor issues reported by PyCharm

aas_core_codegen/intermediate/_translate.py
The translation functions in `intermediate._translate` had a
non-informative prefix where we denoted the *source* of the translation.
This distinction was indeed unnecessary as for each intermediate object
there was only one source.
We thus shortened all the translation functions simply from `_{source
object}_to_{target object}` to `_to_{target object}`.
This made the code substantially more readable.
=> Shorten translation functions in `intermediate`

aas_core_codegen/intermediate/_translate.py
This makes the future refactorings easier to follow, especially when we
add error reporting.
=> Translate enumeration literal in a function

aas_core_codegen/intermediate/_translate.py
We refactor the extraction of the constructor in the
`intermediate._translate` to a separate function. This helps with
conflicting variable names and makes the code easier to read.
=> Separate constructor extraction in intermediate

aas_core_codegen/intermediate/_translate.py
We used two functions (`_over_descriptions` and
`_over_symbol_descriptions`) in `intermediate._translate` only to call
`findall` on the corresponding documents.
In this patch, we integrate the `findall` in a single function,
`_find_all_in_descriptions`. This saves us one indention level and makes
the code even easier to follow.
=> Simplify iteration over intermediate doc elements

aas_core_codegen/intermediate/_translate.py
We split the individual regions of `intermediate._translate._verify`
into separate functions. This is necessary so that we reduce the
variable scope to avoid naming conflicts as well as type conflicts.
=> Refactor `intermediate._translate._verify`

continuous_integration/precommit.py, test_data/csharp/test_main/v3rc2/input/meta_model.py, test_data/intermediate/expected/real_meta_models/v3rc2/meta_model.py, test_data/intermediate/unexpected/properties_and_constructor_arguments_do_not_match/after_inheritance/meta_model.py, test_data/intermediate/unexpected/properties_and_constructor_arguments_do_not_match/within_class/meta_model.py, test_data/jsonschema/test_main/v3rc2/input/meta_model.py, test_data/parse/expected/real_meta_models/v3rc2/meta_model.py, test_data/parse/expected/reference_in_the_book/only_section/meta_model.py, test_data/parse/expected/reference_in_the_book/section_and_index/meta_model.py, test_data/parse/expected/reference_in_the_book/section_index_and_fragment/meta_model.py
This makes the changes in the test data easier to trace.
=> Apply `black` on test meta-models

aas_core_codegen/csharp/jsonization/_generate.py
We had an assertion before warning against a missing feature. This is
not informative for the end user since it seems as if there is
a program bug rather than a missing feature.
With this change, we return an error which is then accompanied by the
line and column for the end user, as they might expect.
=> Return errors instead of raising in C# jsonization

aas_core_codegen/infer_for_schema/_inline.py
We exclude other primitive types from the inference as we currently do
not have a principle approached to constraining other primitive types in
a schema.
=> Infer schema constraints only for strings

test_data/csharp/test_main/v3rc2/expected_output/jsonization.cs, test_data/csharp/test_main/v3rc2/expected_output/stringification.cs, test_data/csharp/test_main/v3rc2/expected_output/types.cs, test_data/csharp/test_main/v3rc2/expected_output/verification.cs, test_data/csharp/test_main/v3rc2/expected_output/visitation.cs, test_data/csharp/test_main/v3rc2/input/meta_model.py, test_data/intermediate/expected/real_meta_models/v3rc2/expected_symbol_table.txt, test_data/intermediate/expected/real_meta_models/v3rc2/meta_model.py, test_data/jsonschema/test_main/v3rc1/input/meta_model.py, test_data/jsonschema/test_main/v3rc2/expected_output/schema.json, test_data/jsonschema/test_main/v3rc2/input/meta_model.py, test_data/parse/expected/real_meta_models/v3rc2/expected_symbol_table.txt, test_data/parse/expected/real_meta_models/v3rc2/meta_model.py, test_data/rdf_shacl/test_main/v3rc1/input/meta_model.py
We want to add aas-core-codegen to the pre-commit checks of
aas-core-meta so we sync the test data to the files in aas-core-meta to
have both versions in sync.
=> Sync test data with `aas-core-meta`

README.rst, aas_core_codegen/jsonschema/main.py, aas_core_codegen/main.py, aas_core_codegen/xsd/__init__.py, aas_core_codegen/xsd/main.py, aas_core_codegen/xsd/naming.py, continuous_integration/check_test_meta_models_coincide.py, dev_scripts/run_tests_with_rerecord.py, test_data/xsd/test_main/v3rc2/expected_output/schema.xml, test_data/xsd/test_main/v3rc2/expected_output/stdout.txt, test_data/xsd/test_main/v3rc2/input/meta_model.py, test_data/xsd/test_main/v3rc2/input/snippets/Lang_string_set.xml, test_data/xsd/test_main/v3rc2/input/snippets/root_element.xml, tests/xsd/test_main.py
This is the initial version of the generator for XML Schema Definition
(XSD).
=> Write XSD generator

aas_core_codegen/intermediate/_translate.py
We add an assertion in the intermediate stage to make sure that the
descendants and concrete descendants are computed correctly. This also
helps the readability of the code, as the users can directly refer to
the assertions in case of uncertainty.
=> Assert that `self` is not in descendants

test_data/xsd/test_main/v3rc2/examples/expected/asset_administration_shell/minimal_asset_administration_shell.xml, test_data/xsd/test_main/v3rc2/examples/expected/concept_description/minimal_concept_description.xml, test_data/xsd/test_main/v3rc2/examples/expected/empty/empty_environment_with_optional_properties_empty.xml, test_data/xsd/test_main/v3rc2/examples/expected/empty/empty_environment_with_optional_properties_missing.xml, test_data/xsd/test_main/v3rc2/examples/expected/submodels/minimal_submodel.xml, test_data/xsd/test_main/v3rc2/examples/expected/submodels/property/minimal_property.xml, test_data/xsd/test_main/v3rc2/examples/expected/submodels/property/property_with_id_short.xml, test_data/xsd/test_main/v3rc2/examples/expected/submodels/submodel_with_two_submodel_elements.xml, test_data/xsd/test_main/v3rc2/expected_output/schema.xsd, test_data/xsd/test_main/v3rc2/input/snippets/Lang_string_set.xml, test_data/xsd/test_main/v3rc2/input/snippets/root_element.xml
We change the snippets and the examples to reflect the correct version
of the XSD.
=> Fix the version for XSD test data

CHANGELOG.rst, aas_core_codegen/__init__.py, setup.py
* Render the descriptions with smoke at intermediate (#142)
C#
--
* Represent string constants as literals in C# (#136)
* Fix formatting of multi-line invariants in C# (#137)
* Break lines on invariants in C# (#139)
* Wrap the invariant descriptions in C# (#140)
JSON Schema
-----------
* Make ``modelType``'s strings in JSON schema (#143)
XSD
---
* Write XSD generator (#126)
* Fix interfaces in XSD (#128)
* Fix XSD to use correct environment type (#130)
* Undo escaping of ``\x??`` in XSD (#131)
=> Release 0.0.7

aas_core_codegen/jsonschema/main.py, test_data/jsonschema/test_main/aas_core_meta.v3rc2/expected_output/schema.json
Sorted definitions are:
1) Easier to diff,
2) Easier to search, and
3) Easier to compare against RDF+SHACL schemas.
=> Sort definitions in JSON schema

.idea/dictionaries/rist.xml, CHANGELOG.rst, aas_core_codegen/__init__.py, setup.py
JSON
----
* Sort definitions in JSON schema (#148)
XSD
---
* Sort schema elements by tag and name in XSD (#149)
=> Release 0.0.8

requirements-dev.txt, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/types.cs, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/verification.cs, test_data/csharp/test_main/aas_core_meta.v3rc2/input/snippets/Types/Concept_description/category_or_default.cs, test_data/csharp/test_main/aas_core_meta.v3rc2/input/snippets/Types/Extension/value_type_or_default.cs, test_data/csharp/test_main/aas_core_meta.v3rc2/input/snippets/Types/Has_kind/kind_or_default.cs, test_data/csharp/test_main/aas_core_meta.v3rc2/input/snippets/Types/Submodel_element_list/order_relevant_or_default.cs, test_data/intermediate/real_meta_models/aas_core_meta.v3rc2/expected_symbol_table.txt, test_data/parse/real_meta_models/aas_core_meta.v3rc2/expected_symbol_table.txt
We update the snippets in the test data for the latest aas-core-meta
release.
=> Update to latest aas-core-meta 2022.5.30a1

CHANGELOG.rst, aas_core_codegen/__init__.py, setup.py
* Move ``requirements-dev`` back to ``setup.py`` (#175)
=> Release 0.0.10

CHANGELOG.rst, aas_core_codegen/__init__.py, setup.py
* Fix a typo in RDF query message (#179)
=> Release 0.0.12

test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/verification.cs, test_data/csharp/test_main/aas_core_meta.v3rc2/input/snippets/Verification/is_model_reference_to.cs, test_data/csharp/test_main/aas_core_meta.v3rc2/input/snippets/Verification/is_xs_date_time_stamp_utc.cs, test_data/csharp/test_main/aas_core_meta.v3rc2/input/snippets/Verification/submodel_elements_have_identical_semantic_ids.cs
This patch contains various minor fixes such that InspectCode does not
complain on the generated code.
=> Fix C# for InspectCode

setup.py, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/types.cs, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/verification.cs, test_data/csharp/test_main/aas_core_meta.v3rc2/input/snippets/Types/Data_element/category_or_default.cs, test_data/csharp/test_main/aas_core_meta.v3rc2/input/snippets/Verification/data_element_category_is_valid.cs, test_data/intermediate/real_meta_models/aas_core_meta.v3rc2/expected_symbol_table.txt, test_data/parse/real_meta_models/aas_core_meta.v3rc2/expected_symbol_table.txt
This patch contains new or fixed snippets for aas-core-meta 2022.6.21.
=> Adapt for aas-core-meta 2022.6.21

setup.py, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/jsonization.cs, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/types.cs, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/verification.cs, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/visitation.cs, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/xmlization.cs, test_data/intermediate/real_meta_models/aas_core_meta.v3rc2/expected_symbol_table.txt, test_data/parse/real_meta_models/aas_core_meta.v3rc2/expected_symbol_table.txt, test_data/rdf_shacl/test_main/aas_core_meta.v3rc2/expected_output/shacl-schema.ttl
This patch is a re-recording of all the files for the latest
aas-core-meta.
=> Generate for latest aas-core-meta 0fa34d1

aas_core_codegen/csharp/xmlization/_generate.py, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/xmlization.cs
We accept a namespace argument in the de-serialization of the XML data.
This is necessary if we are de-serializing a document with multiple
namespaces where "our" elements are prefixed or live beneath a
namespace.
=> Handle namespace in C# xmlization

aas_core_codegen/csharp/jsonization/_generate.py, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/jsonization.cs
We forgot to return on errors which was revealed by unit tests generated
by aas-core-testgen.
=> Fix null handling in C# jsonization of lists

setup.py, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/jsonization.cs, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/types.cs, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/verification.cs, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/xmlization.cs, test_data/intermediate/real_meta_models/aas_core_meta.v3rc2/expected_symbol_table.txt, test_data/jsonschema/test_main/aas_core_meta.v3rc2/expected_output/schema.json, test_data/parse/real_meta_models/aas_core_meta.v3rc2/expected_symbol_table.txt, test_data/rdf_shacl/test_main/aas_core_meta.v3rc2/expected_output/rdf-ontology.ttl, test_data/rdf_shacl/test_main/aas_core_meta.v3rc2/expected_output/shacl-schema.ttl, test_data/xsd/test_main/aas_core_meta.v3rc2/expected_output/schema.xsd
We re-record the test data for [aas-core-meta 5f563af].
[aas-core-meta 5f563af]: https://github.com/aas-core-works/aas-core-meta/commit/5f563af
=> Update to aas-core-meta 5f563af

setup.py, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/jsonization.cs, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/stringification.cs, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/types.cs, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/verification.cs, test_data/csharp/test_main/aas_core_meta.v3rc2/input/snippets/Verification/reference_key_values_equal.cs, test_data/intermediate/real_meta_models/aas_core_meta.v3rc2/expected_symbol_table.txt, test_data/jsonschema/test_main/aas_core_meta.v3rc2/expected_output/schema.json, test_data/parse/real_meta_models/aas_core_meta.v3rc2/expected_symbol_table.txt, test_data/rdf_shacl/test_main/aas_core_meta.v3rc2/expected_output/rdf-ontology.ttl, test_data/xsd/test_main/aas_core_meta.v3rc2/expected_output/schema.xsd
We adapt the test data to [aas-core-meta 93f0af2].
[aas-core-meta 93f0af2]: https://github.com/aas-core-works/aas-core-meta/commit/93f0af2
=> Update to aas-core-meta 93f0af2

setup.py, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/jsonization.cs, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/types.cs, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/verification.cs, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/visitation.cs, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/xmlization.cs, test_data/intermediate/real_meta_models/aas_core_meta.v3rc2/expected_symbol_table.txt, test_data/jsonschema/test_main/aas_core_meta.v3rc2/expected_output/schema.json, test_data/parse/real_meta_models/aas_core_meta.v3rc2/expected_symbol_table.txt, test_data/rdf_shacl/test_main/aas_core_meta.v3rc2/expected_output/rdf-ontology.ttl, test_data/rdf_shacl/test_main/aas_core_meta.v3rc2/expected_output/shacl-schema.ttl, test_data/xsd/test_main/aas_core_meta.v3rc2/expected_output/schema.xsd
We update the test data to the latest [aas-core-meta 0d96564].
[aas-core-meta 0d96564]: https://github.com/aas-core-works/aas-core-meta/commit/0d96564
=> Update test data to aas-core-meta 0d96564

setup.py, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/verification.cs, test_data/intermediate/real_meta_models/aas_core_meta.v3rc2/expected_symbol_table.txt, test_data/parse/real_meta_models/aas_core_meta.v3rc2/expected_symbol_table.txt
We update the test data using the latest [aas-core-meta 1ae5aa0].
[aas-core-meta 1ae5aa0]: https://github.com/aas-core-works/aas-core-meta/commit/1ae5aa0
=> Update test data to aas-core-meta 1ae5aa0

setup.py, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/jsonization.cs, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/types.cs, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/verification.cs, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/xmlization.cs, test_data/intermediate/real_meta_models/aas_core_meta.v3rc2/expected_symbol_table.txt, test_data/jsonschema/test_main/aas_core_meta.v3rc2/expected_output/schema.json, test_data/parse/real_meta_models/aas_core_meta.v3rc2/expected_symbol_table.txt, test_data/rdf_shacl/test_main/aas_core_meta.v3rc2/expected_output/rdf-ontology.ttl, test_data/rdf_shacl/test_main/aas_core_meta.v3rc2/expected_output/shacl-schema.ttl, test_data/xsd/test_main/aas_core_meta.v3rc2/expected_output/schema.xsd
We update the requirements to and re-record the test data for
[aas-core-meta 8d909e9].
[aas-core-meta 8d909e9]: https://github.com/aas-core-works/aas-core-codegen/commit/8d909e9
=> Update test data to aas-core-meta 8d909e9

setup.py, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/verification.cs, test_data/intermediate/real_meta_models/aas_core_meta.v3rc2/expected_symbol_table.txt, test_data/parse/real_meta_models/aas_core_meta.v3rc2/expected_symbol_table.txt
We update the development requirements to and re-record the test data for [aas-core-meta e63c0c9].
[aas-core-meta e63c0c9]: https://github.com/aas-core-works/aas-core-meta/commit/e63c0c9
=> Update test data to aas-core-meta e63c0c9

aas_core_codegen/csharp/common.py, aas_core_codegen/csharp/description.py, aas_core_codegen/csharp/reporting/_generate.py, aas_core_codegen/csharp/structure/_generate.py, aas_core_codegen/csharp/transpilation.py, aas_core_codegen/csharp/unrolling.py, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/reporting.cs
We collect a couple of minor fixes into a single patch. The issues were detected while we were working on Python SDK and revising the generated C# SDK code.
=> Fix C# minor issues while working on Python SDK

setup.py, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/verification.cs, test_data/intermediate/real_meta_models/aas_core_meta.v3rc2/expected_symbol_table.txt, test_data/parse/real_meta_models/aas_core_meta.v3rc2/expected_symbol_table.txt, test_data/python/test_main/aas_core_meta.v3rc2/expected_output/verification.py
We update the development requirements to and re-record the test data for [aas-core-meta b2d1230].
[aas-core-meta b2d1230]: https://github.com/aas-core-works/aas-core-meta/commit/b2d1230
=> Update test data to aas-core-meta b2d1230

setup.py, test_data/csharp/test_main/aas_core_meta.v3rc2/expected_output/types.cs, test_data/intermediate/real_meta_models/aas_core_meta.v3rc2/expected_symbol_table.txt, test_data/python/test_main/aas_core_meta.v3rc2/expected_output/types.py
We update the development requirements to and re-record the test data for [aas-core-meta e3707bf].
[aas-core-meta e3707bf]: https://github.com/aas-core-works/aas-core-meta/commit/e3707bf
=> Update test data to aas-core-meta e3707bf

test_data/python/test_main/aas_core_meta.v3/expected_output/types.py, test_data/python/test_main/aas_core_meta.v3/expected_output/verification.py, test_data/python/test_main/aas_core_meta.v3/input/snippets/Types/Extension/value_type_or_default.py, test_data/python/test_main/aas_core_meta.v3/input/snippets/Types/Has_kind/kind_or_default.py, test_data/python/test_main/aas_core_meta.v3/input/snippets/Verification/ID_shorts_of_variables_are_unique.py, test_data/python/test_main/aas_core_meta.v3/input/snippets/Verification/lang_strings_have_unique_languages.py, test_data/python/test_main/aas_core_meta.v3/input/snippets/Verification/properties_or_ranges_have_value_type.py, test_data/python/test_main/aas_core_meta.v3/input/snippets/Verification/submodel_element_is_of_type.py, test_data/python/test_main/aas_core_meta.v3/input/snippets/Verification/value_consistent_with_XSD_type.py
We only generated the code, but haven't tested it with mypy.
This patch consists of many minor, but important, fixes which make the mypy smile again.
=> Fix Python snippets in test data for mypy

test_data/csharp/test_main/aas_core_meta.v3/expected_output/types.cs, test_data/csharp/test_main/aas_core_meta.v3/expected_output/verification.cs, test_data/csharp/test_main/aas_core_meta.v3/input/snippets/Types/Has_kind/kind_or_default.cs, test_data/csharp/test_main/aas_core_meta.v3/input/snippets/Verification/ID_shorts_of_variables_are_unique.cs, test_data/csharp/test_main/aas_core_meta.v3/input/snippets/Verification/is_xs_date_time.cs, test_data/csharp/test_main/aas_core_meta.v3/input/snippets/Verification/lang_strings_have_unique_languages.cs
We fix the snippets for C# and test them in aas-core3.0-csharp.
=> [V3] Fix snippets for C#

test_data/typescript/test_main/aas_core_meta.v3/expected_output/jsonization.ts, test_data/typescript/test_main/aas_core_meta.v3/expected_output/verification.ts
We re-record test data to reflect changes in #361.
=> Re-record test data after #361

setup.py
We update the development requirements to and re-record the test data for [aas-core-meta 2a81612].
[aas-core-meta 2a81612]: https://github.com/aas-core-works/aas-core-meta/commit/2a81612
=> Update test data to aas-core-meta 2a81612

aas_core_codegen/intermediate/type_inference.py
We make `intermediate.type_inference` stricter w.r.t. nullability (non-None) checks. This is motivated by bugs occurring in aas-core-meta, such as [271], [272] and [273].
[271]: https://github.com/aas-core-works/aas-core-meta/pull/271
[272]: https://github.com/aas-core-works/aas-core-meta/pull/272
[273]: https://github.com/aas-core-works/aas-core-meta/pull/273
=> Make nullability checks stricter in type inference

setup.py
We update the development requirements to and re-record the test data for [aas-core-meta 85bdaf2].
[aas-core-meta 85bdaf2]: https://github.com/aas-core-works/aas-core-meta/commit/85bdaf2
=> Update test data to aas-core-meta 85bdaf2

README.rst, aas_core_codegen/jsonld/__init__.py, aas_core_codegen/jsonld/main.py, aas_core_codegen/main.py, setup.py, test_data/jsonld_context/context.jsonld, tests/jsonld_context/test_main.py
This PR leads to add JSON-LD context generation feature using the meta model from aas-core-meta.
=> Generate AAS JSON-LD context from meta model

CONTRIBUTING.rst
We write up the current style guide used in the code base.
=> Include style guide in contributing document

aas_core_codegen/cpp/xmlization/_generate.py, test_data/cpp/test_main/aas_core_meta.v3/expected_output/xmlization.cpp
We fix the generator for C++ xmlization code according to the bugs discovered during the thorough testing with aas-core3.0-testgen data.
=> Fix xmlization in C++ generator after testing

dev_scripts/update_to_aas_core_meta.py
We give more information to the developer if one of the re-recordings in the update script fails so that the error is easier to debug.
=> Report what failed in the update script

aas_core_codegen/jsonld/main.py
We replace the dictionaries with ordered dictionaries so that repeated generations result always in the same schema.
=> Make JSON-LD generator deterministic

CONTRIBUTING.rst
We specify in more detail the guidelines on commit messages to reflect the current message history of the project.
=> Update guidelines on commit messages

aas_core_codegen/intermediate/_translate.py
We fix the verification of mismatching constructor arguments and properties by reporting early (and skipping further checks) when properties are not initialized in a constructor or the constructor is missing for a class.
=> Report early missing constructors

aas_core_codegen/typescript/jsonization/_generate.py, test_data/typescript/test_main/aas_core_meta.v3/expected_output/jsonization.ts
Please see #510 for more details. This is a fix particularly for TypeScript generation.
=> Check explicitly for model type in TypeScript

aas_core_codegen/intermediate/type_inference.py, tests/intermediate/test_type_inference.py
We forgot to check that the value type is an optional type in type inference. This causes various compilation errors in some of the strongly typed languages as you can not compare non-null types with null (*e.g.*, in C++ or Go).
In this patch, we fix the type inference to correctly detect the invalid (non-)nullness checks and report them.
=> Check for optional type in nullness checks

setup.py, test_data/cpp/test_main/aas_core_meta.v3/expected_output/verification.cpp, test_data/csharp/test_main/aas_core_meta.v3/expected_output/verification.cs, test_data/golang/test_main/aas_core_meta.v3/expected_output/verification/verification.go, test_data/intermediate/real_meta_models/aas_core_meta.v3/expected_symbol_table.txt, test_data/java/test_main/aas_core_meta.v3/expected_output/verification/Verification.java, test_data/jsonschema/test_main/aas_core_meta.v3/expected_output/schema.json, test_data/opcua/test_main/aas_core_meta.v3/expected_output/nodeset.xml, test_data/parse/real_meta_models/aas_core_meta.v3/expected_symbol_table.txt, test_data/python/test_main/aas_core_meta.v3/expected_output/verification.py, test_data/rdf_shacl/test_main/expected/aas_core_meta.v3/expected_output/shacl-schema.ttl, test_data/typescript/test_main/aas_core_meta.v3/expected_output/verification.ts
We update the development requirements to and re-record the test data for [aas-core-meta 5d409d6].
Notably, this is the propagation of final bug fixes in aas-core-meta for V3.0.2.
[aas-core-meta 5d409d6]: https://github.com/aas-core-works/aas-core-meta/commit/5d409d6
=> Update test data to aas-core-meta 5d409d6

aas_core_codegen/jsonschema/main.py
So far, we always translated the patterns in JSON schema to surrogate pairs, where characters above the Basic Multilingual Plane are encoded with two characters.
This does not work for some downstream clients whose JSON Schema engine requires a different pattern. For example, using `jsonschema` library in `aas-core3.0-testgen` can not translate the surrogate pairs back to Unicode characters in patterns, and thus fails on actually valid JSON schema.
In this change, we make the `generate` function public and allow the client to supply their own function for how the patterns should be translated (*i.e.*, "fixed").
=> Allow for custom pattern fixing in jsonschema
